### ISSUE TITLE
instancing_mesh example crashes with exception

### ISSUE THREAD

**Issue by alansartorio** [pygfx/pygfx#256]
When I try to run the [instancing_mesh.py](https://github.com/pygfx/pygfx/blob/46a9c84cd125dd317bb0026bab2a0f8be084ab04/examples/instancing_mesh.py) example I get this traceback:

```sh
❯ python instancing_mesh.py
Draw error
Traceback (most recent call last):
  File "/home/alan/.local/lib/python3.10/site-packages/wgpu/gui/base.py", line 113, in _draw_frame_and_present
    self.draw_frame()
  File "/home/alan/Documents/PyGFXTests/instancing_mesh.py", line 40, in animate
    renderer.render(scene, camera)
  File "/home/alan/.local/lib/python3.10/site-packages/pygfx/renderers/wgpu/_renderer.py", line 446, in render
    wobject_pipeline, has_changed = ensure_pipeline(self, wobject)
  File "/home/alan/.local/lib/python3.10/site-packages/pygfx/renderers/wgpu/_pipelinebuilder.py", line 36, in ensure_pipeline
    new_pipeline_infos = create_pipeline_infos(shared, blender, wobject)
  File "/home/alan/.local/lib/python3.10/site-packages/pygfx/renderers/wgpu/_pipelinebuilder.py", line 111, in create_pipeline_infos
    pipeline_infos = renderfunc(render_info)
  File "/home/alan/.local/lib/python3.10/site-packages/pygfx/renderers/wgpu/meshrender.py", line 125, in mesh_renderer
    shader.define_binding(0, i, binding)
  File "/home/alan/.local/lib/python3.10/site-packages/pygfx/renderers/wgpu/_shadercomposer.py", line 337, in define_binding
    self._define_buffer(bindgroup, index, binding)
  File "/home/alan/.local/lib/python3.10/site-packages/pygfx/renderers/wgpu/_shadercomposer.py", line 450, in _define_buffer
    fmt = to_vertex_format(binding.resource.format)
  File "/home/alan/.local/lib/python3.10/site-packages/pygfx/resources/_buffer.py", line 121, in format
    self._format = format_from_memoryview(self.mem)
  File "/home/alan/.local/lib/python3.10/site-packages/pygfx/resources/_buffer.py", line 204, in format_from_memoryview
    raise TypeError(
TypeError: Cannot convert 'T{(4,4)f:matrix:I:id:(12)B:_12_bytes_padding:}' to vertex format. Maybe specify format?
```

The program does not crash if I use a gfx.Mesh instead (but obviously I don't get instancing).

**Comment by almarklein** [comment]
I can reproduce that it's broken. Thanks for reporting!
