### ISSUE TITLE
dealing with non-contiguous arrays

### ISSUE THREAD

**Issue by kushalkolar** [pygfx/pygfx#307]
I got this issue when dealing when setting data for Geometry to create a line using output from sklearn's `PCA.transform()`. It can be fixed using `np.ascontiguousarray(data)` but I'm not sure if this could effect other use cases too. The exception I receive is:

```
ERROR:wgpu:Draw error: memoryview: underlying buffer is not C-contiguous
```

I'll try to get a minimal code example that produces this, I was using some of my own data.

**Comment by Korijn** [comment]
On the GPU all buffers must be c-contiguous. Since making an array contiguous requires a big memory allocation step and a copy step, it can be pretty slow, so users should ideally decide where in their code to do that themselves.

We could make the error a little friendlier?

**Comment by almarklein** [comment]
We indeed chose to not automatically make arrays contiguous. In part because of the overhead, but also because if you do something like:
```py
array = ...
buffer = gfx.Buffer(array)
array is buffer.data
```
The last line is now always True. If we'd automatically make arrays contiguous, the last line would be valid is some cases, and invalid in others.

But I agree that we could check it and raise a friendly error message.

**Comment by almarklein** [comment]
This actually looks pretty ok:
https://github.com/pygfx/pygfx/blob/1135d3049cf571a4a850f3c08316df779ea4c298/pygfx/resources/_buffer.py#L169-L185

Non-contiguous arrays are actually allowed, and we use them in some of our examples.

It looks like the error originates at another part in the code, maybe in the `Buffer.__init__`? And maybe its related to the array not being a numpy array? If this error can be replicated with a small code snippet that'd be great 👍

**Comment by kushalkolar** [comment]
Finally got around to looking at this again

Simple example:

```python
import numpy as np
from wgpu.gui.auto import WgpuCanvas, run
import pygfx as gfx


canvas = WgpuCanvas()
renderer = gfx.WgpuRenderer(canvas)

scene = gfx.Scene()

xs = np.linspace(0, 20 * np.pi, 500)
ys = np.sin(xs) * 10
zs = np.zeros(xs.size)

# this won't work
positions = np.vstack([xs, ys, zs]).astype(np.float32).T

# this will work
# positions = np.ascontiguousarray(positions)

sizes = np.array([5] * xs.size).astype(np.float32)
colors = np.random.rand(xs.size, 4).astype(np.float32)

geometry = gfx.Geometry(positions=positions, sizes=sizes, colors=colors)

material = gfx.PointsMaterial(color_mode="vertex", vertex_sizes=True)
points = gfx.Points(
    gfx.Geometry(positions=positions, sizes=sizes, colors=colors),
    material=gfx.PointsMaterial(color_mode="vertex", vertex_sizes=True)
)

scene.add(points)


camera = gfx.OrthographicCamera()
camera.show_object(scene)


if __name__ == "__main__":
    canvas.request_draw(lambda: renderer.render(scene, camera))
    run()
```

Results in:

```python
Draw error
Traceback (most recent call last):
  File "/home/kushal/venvs/mescore/lib/python3.11/site-packages/wgpu/gui/base.py", line 24, in log_exception
    yield
  File "/home/kushal/venvs/mescore/lib/python3.11/site-packages/wgpu/gui/base.py", line 211, in _draw_frame_and_present
    self.draw_frame()
  File "/home/kushal/repos/pygfx/examples/introductory/points_basic.py", line 43, in <lambda>
    canvas.request_draw(lambda: renderer.render(scene, camera))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/_renderer.py", line 523, in render
    update_resource(resource)
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/_update.py", line 32, in update_resource
    return _update_buffer(resource)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/_update.py", line 80, in _update_buffer
    device.queue.write_buffer(
  File "/home/kushal/venvs/mescore/lib/python3.11/site-packages/wgpu/backends/wgpu_native/_api.py", line 2665, in write_buffer
    m, address = get_memoryview_and_address(data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/venvs/mescore/lib/python3.11/site-packages/wgpu/backends/wgpu_native/_helpers.py", line 66, in get_memoryview_and_address
    c_data = ffi.from_buffer("uint8_t []", m)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/venvs/mescore/lib/python3.11/site-packages/cffi/api.py", line 365, in from_buffer
    return self._backend.from_buffer(cdecl, python_buffer,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
BufferError: memoryview: underlying buffer is not C-contiguous
No texture to present, missing call to get_current_texture()?
```


Here's a real use case example with PCA where the buffer of the projection is not contiguous:

```python
import numpy as np
from wgpu.gui.auto import WgpuCanvas, run

import pygfx
import pygfx as gfx

from sklearn.datasets import load_iris
from sklearn.decomposition import PCA


data, target = load_iris()["data"], load_iris()["target"]
pca = PCA(n_components=3)
positions = pca.fit_transform(data).astype(np.float32)


# making a C-contiguous buffer works
# positions = np.ascontiguousarray(positions)

canvas = WgpuCanvas()
renderer = gfx.WgpuRenderer(canvas)

scene = gfx.Scene()

sizes = np.array([5] * positions.shape[0]).astype(np.float32)

cmap = {
    0: np.array(pygfx.Color("blue")),
    1: np.array(pygfx.Color("red")),
    2: np.array(pygfx.Color("yellow"))
}

colors = np.array(list(map(cmap.get, target)))

geometry = gfx.Geometry(positions=positions, sizes=sizes, colors=colors)

material = gfx.PointsMaterial(color_mode="vertex", vertex_sizes=True)
points = gfx.Points(
    gfx.Geometry(positions=positions, sizes=sizes, colors=colors),
    material=gfx.PointsMaterial(color_mode="vertex", vertex_sizes=True)
)

scene.add(points)


camera = gfx.OrthographicCamera()
camera.show_object(scene)


if __name__ == "__main__":
    canvas.request_draw(lambda: renderer.render(scene, camera))
    run()
```

Results in an identical traceback:

```python
Draw error
Traceback (most recent call last):
  File "/home/kushal/venvs/mescore/lib/python3.11/site-packages/wgpu/gui/base.py", line 24, in log_exception
    yield
  File "/home/kushal/venvs/mescore/lib/python3.11/site-packages/wgpu/gui/base.py", line 211, in _draw_frame_and_present
    self.draw_frame()
  File "/home/kushal/repos/pygfx/examples/feature_demo/line_basic.py", line 50, in <lambda>
    canvas.request_draw(lambda: renderer.render(scene, camera))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/_renderer.py", line 523, in render
    update_resource(resource)
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/_update.py", line 32, in update_resource
    return _update_buffer(resource)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/_update.py", line 80, in _update_buffer
    device.queue.write_buffer(
  File "/home/kushal/venvs/mescore/lib/python3.11/site-packages/wgpu/backends/wgpu_native/_api.py", line 2665, in write_buffer
    m, address = get_memoryview_and_address(data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/venvs/mescore/lib/python3.11/site-packages/wgpu/backends/wgpu_native/_helpers.py", line 66, in get_memoryview_and_address
    c_data = ffi.from_buffer("uint8_t []", m)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/venvs/mescore/lib/python3.11/site-packages/cffi/api.py", line 365, in from_buffer
    return self._backend.from_buffer(cdecl, python_buffer,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
BufferError: memoryview: underlying buffer is not C-contiguous
No texture to present, missing call to get_current_texture()?
```

**Comment by almarklein** [comment]
Thanks @kushalkolar! I made a pr that does the check at a much earlier moment, when the buffer is created, resulting in a friendlier message.
