### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by sharon92** [pygfx/pygfx#521]
I am new to pygfx and wanted to try out plotting a large mesh file.

My mesh file has triangles and patches (quadrilaterals).

I am plotting it like this:

```
from wgpu.gui.auto import WgpuCanvas, run
import pygfx as gfx
import trimesh
from MeshParser import parser
import numpy as np

path = "path_to_mesh.2dm"
meshObj = parser.meshReader(path)

t = trimesh.Trimesh(vertices=meshObj.nd[:,1:],
                    faces = meshObj.e3t[:,1:-1]-1)

canvas = WgpuCanvas(title='Mesh Viewer v0.0')
renderer = gfx.renderers.WgpuRenderer(canvas)

mesh = gfx.Mesh(
    gfx.geometry_from_trimesh(t),
    gfx.MeshBasicMaterial(wireframe=True,clipping_mode='all'),
)

patches = gfx.WorldObject(
    gfx.Geometry(indices=meshObj.e4q[:,1:-1]-1, positions=meshObj.nd[:,1:].astype(np.float32)),
    gfx.Material(clipping_mode="all")
    )

box_local = gfx.BoxHelper(thickness=2, color="green")
box_local.set_transform_by_object(mesh, space="local")
mesh.add(box_local)

scene = gfx.Scene()
scene.add(gfx.AmbientLight())
scene.add(gfx.DirectionalLight())
dark_gray = np.array((169, 167, 168, 255)) / 255
light_gray = np.array((100, 100, 100, 255)) / 255
background = gfx.Background(None, gfx.BackgroundMaterial(light_gray, dark_gray))

scene.add(background)

camera = gfx.PerspectiveCamera(far=10000)#near=0.1,far=100)
# camera.show_object(scene)
# camera = gfx.NDCCamera()
# camera.local.z = 4 #this doesnt work, local doesnt exist

scene.add(mesh,patches)
# controller = gfx.OrbitController(camera)
# controller.add_default_event_handlers(renderer)


if __name__ == "__main__":
    # renderer.render(scene, camera)
    # canvas.request_draw(lambda: renderer.render(mesh, camera))
    # run()
    gfx.show(scene,renderer=renderer, camera=camera)
```

This only renders the triangles but it cant render the patches:
```
Draw error
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\wgpu\gui\base.py", line 23, in log_exception
    yield
  File "C:\Python311\Lib\site-packages\wgpu\gui\base.py", line 173, in _draw_frame_and_present
    self.draw_frame()
  File "C:\Python311\Lib\site-packages\pygfx\utils\show.py", line 84, in default_draw
    self.renderer.render(self.scene, self.camera)
  File "C:\Python311\Lib\site-packages\pygfx\renderers\wgpu\_renderer.py", line 498, in render
    container_group = get_pipeline_container_group(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pygfx\renderers\wgpu\_pipeline.py", line 42, in get_pipeline_container_group
    pipeline_container_group.update(wobject, environment, shared, changed_labels)
  File "C:\Python311\Lib\site-packages\pygfx\renderers\wgpu\_pipeline.py", line 235, in update
    raise ValueError(
ValueError: Could not get a render function for WorldObject with Material
```

I am wondering if I need to have a custom render function.

Also the triangles dont render at certain angles:
Normal:
![image](https://user-images.githubusercontent.com/51754340/236156382-7770c82b-3415-4dce-a109-55a7ac37aad8.png)

triangles missing:
![image](https://user-images.githubusercontent.com/51754340/236156279-5206e87e-808b-4c9b-b2d0-cd377060e1fc.png)

If there are some quick fixes to this or if you could point me to the right direction would be great!

Thank you for the wonderful library! :)

**Comment by almarklein** [comment]
Pygfx does not support quadrilaterals. They are not supported by the modern graphics API's (Vulkan/Metal/DX12). In order to render these, I see two possible approaches:

* Triangulate them (just convert each quad into two triangles), and then render as a normal mesh.
* A custom shader, somewhat similar to e.g. our line shader (though much simpler), that produces triangles based on the quad data. 

The triangles disappearing at certain angles sounds to a depth-buffer thing on first sight, but there does not seem to be anything else in the scene so that's certainly strange. A minimal example to reproduce the effect would help us investigate ...

**Comment by sharon92** [comment]
Thanks for the tips. Yesterday I did exactly the same. I used gfx.Mesh object to render quads, in order to do so I calculated the normals beforehand. Now it looks like this:

![image](https://user-images.githubusercontent.com/51754340/236394678-2a26e038-0557-41e7-8933-fea015859861.png)

It's supposed to be a river bed (we model them with patches or quads). It would be still nice if there was a possibility to render them without triangulating them or not painting the diagonals somehow.

By downloading the development version, I was able to play with depth_range keyword and increasing the far range to 100000 solved the visibility problem. Still don't quite understand how it works because I was zoomed in to the mesh

**Comment by almarklein** [comment]
> [...] or not painting the diagonals somehow.

Ah, good point. I created #523 to track this. A quick solution for you could be to create a custom object to draw the wireframe of patches. The long-term solution would be to support quads in pygfx meshes, I think.

> By downloading the development version, I was able to play with depth_range keyword and increasing the far range to 100000 solved the visibility problem. Still don't quite understand how it works because I was zoomed in to the mesh

Basically, the depth buffer has limited bits to store how far a fragment is from the camera. The available bits are used between the near and far plane, and the space is divided exponentially (more bits for things closer to the camera). The optimal `camera.depth_range`  depends on how large your scene is and how far you want to zoom in. The `camera.show_x()` methods guess appropriate values. But if that is not good enough, you may need to explicitly set `camera.depth_range`.

**Comment by sharon92** [comment]
@almarklein I tried the custom object way but I am not so sure how the bindings and other low level interactions work. With this example https://pygfx.readthedocs.io/en/latest/_gallery/feature_demo/custom_object3.html i got the idea that `wgpu.PrimitiveTopology` needs to have support for quads or Polygons. So I stopped there.

Thank you for the explanation on how depth_range works!
Btw I am really excited to use this library. It can handle more than 20 million mesh elements with ease. Commercial Softwares (most are based on openGL) for Flood Modelling can't handle it at the moment so I am looking for alternatives :)

**Comment by almarklein** [comment]
>  It can handle more than 20 million mesh elements with ease. Commercial Softwares (most are based on openGL) for Flood Modelling can't handle it at the moment so I am looking for alternatives :)

Wow, that's nice to hear! That's another data-point that suggest that our mesh renderer is pretty efficient - and the use of storage buffers (instead of vertex buffers) does not seem to have a negative effect on performance 🚀

> [...] i got the idea that wgpu.PrimitiveTopology needs to have support for quads or Polygons. So I stopped there.

No, that's the thing 😃 there are no quad primitives. The approach would be to:
* Use triangles as the primitive.
* Draw 2 times as many triangles as there are quads. So in `get_render_info`, the `n` would be `6 * number_of_quads`.
* In the shader you get the quad index by doing `index / 6`. Also calculate the subindex using modulo 6.
* Then map the subindex to the appropriate vertex.

The code in the mesh shader that relates to this:

https://github.com/pygfx/pygfx/blob/92c86a6fb45def2e30bdec4c9509ad7cfdf316ee/pygfx/renderers/wgpu/meshshader.py#L211-L214

**Comment by sharon92** [comment]
@almarklein Cool I was able to paint the quads in a "hacky" way with your tips.

I didn't make a custom object but modified the base geometry and the `BaseShader`.

https://github.com/pygfx/pygfx/blob/92c86a6fb45def2e30bdec4c9509ad7cfdf316ee/pygfx/geometries/_base.py#L46-L51

Here I added:

```
                if name == 'indices' and val.shape[1]==4:
                    #triangulate quads
                    val = np.vstack((val[:,:3],val[:,[0,2,3]]))
```

modified this:
https://github.com/pygfx/pygfx/blob/92c86a6fb45def2e30bdec4c9509ad7cfdf316ee/pygfx/renderers/wgpu/meshshader.py#L133-L136

to:

```
        n = geometry.indices.data.size 
        self["indexer"] = 3
        if geometry.indices.data.shape[1] == 4:
            #2 times as many triangles as there are quads
            n = geometry.indices.data.shape[0] * 6
            self["indexer"] = 6
```

added an argument to code_vertex   `def code_vertex(self,indexer=3):`

and then used an f-string to get the face_index and sub_index
```

 // Select what face we're at
            let index = i32(in.vertex_index);"""+\
            f"""
            
            let face_index = index / {indexer};
            var sub_index = index % {indexer};
            """+\
            """
```

plugging in 6 when quads:

```
    def get_code(self):
        return (
            self.code_definitions()
            + self.code_common()
            + self.code_lighting()
            + self.code_vertex(indexer=self["indexer"])
            + self.code_fragment()
        )

```
Now the triangulated quads paint nicely (painted them blue to separate them from triangular inputs)
![image](https://user-images.githubusercontent.com/51754340/236672935-aeb600f0-f3dc-40a2-b9de-16726e522ad7.png)

Any tips on how to make the diagonals of quads disappear? 
I was thinking maybe I could paint the diagonals as Line geometries and overlay them and somehow make them disappear using the background colour.

**Comment by sharon92** [comment]
ok I just realised that if I am triangulating the quads. It doesnt make sense to change anything in `code_vertex ` or `n` vertices. Maybe i need to make a custom object and shader using `wgpu.PrimitiveTopology.line_list`

**Comment by sharon92** [comment]
Could you have a look into what I did?

```
            // Select what face we're at
            let index = i32(in.vertex_index);
            let face_index = index / {{indexer}};
            var sub_index = index % {{indexer}};
            
            // for quads assuming the vertices are oriented, the triangles are 0 1 2 and 0 2 3
            if sub_index == 3 {
                sub_index = 0;
                } else if sub_index == 4 {
                sub_index = 2;
                } else if sub_index == 5 {
                sub_index = 3;
                }
```

ndc_pos

```
            // For the wireframe we also need the ndc_pos of the other vertices of this face
            $$ if wireframe
                $$ if indexer == 3
                    $$ for i in (1, 2, 3)
                        let raw_pos{{ i }} = load_s_positions(i32(ii[{{ i - 1 }}]));
                        let world_pos{{ i }} = world_transform * vec4<f32>(raw_pos{{ i }}, 1.0);
                        let ndc_pos{{ i }} = u_stdinfo.projection_transform * u_stdinfo.cam_transform * world_pos{{ i }};
                    $$ endfor
                    let depth_offset = -0.0001;  // to put the mesh slice atop a mesh
                    ndc_pos.z = ndc_pos.z + depth_offset;
                $$ elif indexer == 6
                    $$ for i in (1, 2, 3, 4)
                        let raw_pos{{ i }} = load_s_positions(i32(ii[{{ i - 1 }}]));
                        let world_pos{{ i }} = world_transform * vec4<f32>(raw_pos{{ i }}, 1.0);
                        let ndc_pos{{ i }} = u_stdinfo.projection_transform * u_stdinfo.cam_transform * world_pos{{ i }};
                    $$ endfor
                    let depth_offset = -0.0001;  // to put the mesh slice atop a mesh
                    ndc_pos.z = ndc_pos.z + depth_offset;
                $$ endif
            $$ endif
```

distance

```
            // Set wireframe barycentric-like coordinates
            $$ if wireframe
                $$ if indexer == 3
                    $$ for i in (1, 2, 3)
                        let p{{ i }} = (ndc_pos{{ i }}.xy / ndc_pos{{ i }}.w) * u_stdinfo.logical_size * 0.5;
                    $$ endfor
                    let dist1 = abs((p3.x - p2.x) * (p2.y - p1.y) - (p2.x - p1.x) * (p3.y - p2.y)) / distance(p2, p3);
                    let dist2 = abs((p3.x - p1.x) * (p1.y - p2.y) - (p1.x - p2.x) * (p3.y - p1.y)) / distance(p1, p3);
                    let dist3 = abs((p1.x - p2.x) * (p2.y - p3.y) - (p2.x - p3.x) * (p1.y - p2.y)) / distance(p2, p1);
                    var arr_wireframe_coords = array<vec3<f32>, 3>(
                        vec3<f32>(dist1, 0.0, 0.0), vec3<f32>(0.0, dist2, 0.0), vec3<f32>(0.0, 0.0, dist3)
                    );
                    varyings.wireframe_coords = vec3<f32>(arr_wireframe_coords[sub_index]);  // in logical pixels
                $$ elif indexer == 6
                    $$ for i in (1, 2, 3, 4)
                        let p{{ i }} = (ndc_pos{{ i }}.xy / ndc_pos{{ i }}.w) * u_stdinfo.logical_size * 0.5;
                    $$ endfor
                    //dist of vertex 1 to segment 23
                    let dist1_23 = abs((p3.x - p2.x) * (p2.y - p1.y) - (p2.x - p1.x) * (p3.y - p2.y)) / distance(p2, p3);
                    //dist of vertex 1 to segment 34
                    let dist1_34 = abs((p3.x - p4.x) * (p4.y - p1.y) - (p4.x - p1.x) * (p3.y - p4.y)) / distance(p4, p3);

                    //dist of vertex 2 to segment 34
                    let dist2_34 = abs((p4.x - p3.x) * (p3.y - p2.y) - (p3.x - p2.x) * (p4.y - p3.y)) / distance(p3, p4);
                    //dist of vertex 2 to segment 14
                    let dist2_14 = abs((p4.x - p1.x) * (p1.y - p2.y) - (p1.x - p2.x) * (p4.y - p1.y)) / distance(p1, p4);
                    
                    //dist of vertex 3 to segment 12
                    let dist3_12 = abs((p1.x - p2.x) * (p2.y - p3.y) - (p2.x - p3.x) * (p1.y - p2.y)) / distance(p2, p1);
                    //dist of vertex 3 to segment 14
                    let dist3_14 = abs((p1.x - p4.x) * (p4.y - p3.y) - (p4.x - p3.x) * (p1.y - p4.y)) / distance(p4, p1);

                    //dist of vertex 4 to segment 12
                    let dist4_12 = abs((p2.x - p1.x) * (p1.y - p4.y) - (p1.x - p4.x) * (p2.y - p1.y)) / distance(p1, p2);
                    //dist of vertex 4 to segment 23
                    let dist4_23 = abs((p2.x - p3.x) * (p3.y - p4.y) - (p3.x - p4.x) * (p2.y - p3.y)) / distance(p2, p3);
                    
                    //segments 12 23 34 41
                     var arr_wireframe_coords = array<vec4<f32>, 4>(
                        vec4<f32>(0.0, dist1_23, dist1_34, 0.0), 
                        vec4<f32>(0.0, dist2_34, dist2_14, 0.0), 
                        vec4<f32>(0.0, dist3_14,dist3_12, 0.0), 
                        vec4<f32>(0.0, dist4_12,dist4_23, 0.0)
                        );
                    varyings.wireframe_coords = vec4<f32>(arr_wireframe_coords[sub_index]);  // in logical pixels
                $$ endif
            $$ endif
```

Its not plotting wireframe:
![image](https://github.com/pygfx/pygfx/assets/51754340/3b0335ab-3559-4a60-8479-43f02e2ef5d3)

**Comment by sharon92** [comment]
oh i found the mistake in arranging the wireframe coords:

```
                    //segments 12 23 34 41
                    var arr_wireframe_coords = array<vec4<f32>, 4>(
                        vec4<f32>(dist1_23, dist1_34, 0.0, 0.0), 
                        vec4<f32>(0.0, dist2_34, dist2_14, 0.0), 
                        vec4<f32>(0.0, 0.0 , dist3_14,dist3_12), 
                        vec4<f32>(dist4_23, 0.0 ,0.0, dist4_12)
                        );
```

Now I finally have patches!!
![image](https://github.com/pygfx/pygfx/assets/51754340/fc85e3e5-8b12-4fcd-939a-11471bdfdac8)

**Comment by sharon92** [comment]
okay its still missing something. Some edges are missing and some seems to be have painted twice.

screenshot from original software:
![image](https://github.com/pygfx/pygfx/assets/51754340/e1039673-5cc0-4849-b5ff-e842b3e1aae3)

missing edges:

**Comment by sharon92** [comment]
@Korijn I made a branch (my first so i am not sure if I did things right) https://github.com/sharon92/pygfx/tree/sharon92-quads-1

you can run my example in quad_test\MeshQt6.py

**Comment by almarklein** [comment]
Nice to see you managed to show the quads in such a short amount of time!

Could the missing edges be related to the depth issue again? You could try playing with that `depth_offset`.

**Comment by sharon92** [comment]
do you mean `depth_range`? Hmm I am suspecting the edges are not painted, they are not visible at any angle.

**Comment by Korijn** [comment]
> @Korijn I made a branch (my first so i am not sure if I did things right) https://github.com/sharon92/pygfx/tree/sharon92-quads-1

Looking at your code there are two suspicious things that stand out to me:

[Code](https://github.com/pygfx/pygfx/compare/main...sharon92:pygfx:sharon92-quads-1#diff-2528a6523ec29ebcaa1d360cb544ff4d763363c5a3ba85c0408798d024d0c2a8R230-R237) Are you sure the quads are oriented in 
your geometry buffer? This might explain why some quads are rendered correctly, and some are not.

[Code](https://github.com/pygfx/pygfx/compare/main...sharon92:pygfx:sharon92-quads-1#diff-2528a6523ec29ebcaa1d360cb544ff4d763363c5a3ba85c0408798d024d0c2a8R247) You can comment out this part of the shader temporarily to see if the automatic winding correction is perhaps failing for your case. You're not using negative scale in your camera matrices right now so you should be able to disable that line in the shader temporarily just to check if this is the cause.

**Comment by sharon92** [comment]
@Korijn for the patches not showing up. I checked if they are indeed oriented ccw and they are. But yeah maybe I should test them again before drawing.

your second link doesn't show which lines exactly.

**Comment by Korijn** [comment]
Sorry. Line 247:

`sub_index = select(sub_index, -1 * (sub_index - 1) + 1, winding_world * winding_cam < 0.0);`

**Comment by almarklein** [comment]
> do you mean `depth_range`? Hmm I am suspecting the edges are not painted, they are not visible at any angle.

I meant the `depth_offset` hardcoded in the shader.

**Comment by sharon92** [comment]
@almarklein `depth_offset` also didn't make the edges visible.

I played around by arranging the distances in `arr_wireframe_coords`

```
                    //segments 12 23 34 41
                    var arr_wireframe_coords = array<vec4<f32>, 4>(
                        vec4<f32>(dist1_23, 0.0, 0.0,dist1_34), 
                        vec4<f32>(dist2_14, dist2_34,  0.0, 0.0), 
                        vec4<f32>(0.0, dist3_12, dist3_14, 0.0), 
                        vec4<f32>( 0.0 ,0.0, dist4_23, dist4_12)
                        );
```

this painted the edges which were previously missing but created new missing edges:
![image](https://github.com/pygfx/pygfx/assets/51754340/ef8334d2-c8ca-46ff-a8b8-67eccbcf8d44)

Do you know the logic of how the distances are arranged?

I also thought maybe the distance to the line is not the correct distance and added a code to measure distance to the line segment, but that didn't make any difference.


```
        fn dist_pt_line(x1: f32, y1: f32, x2: f32, y2: f32, x3: f32, y3: f32) -> f32 {
         // Distance of pt (x3,y3) to line with coords(x1,y1) (x2,y2)
         return abs((x2 - x1) * (y1 - y3) - (x1 - x3) * (y2 - y1)) / sqrt((x2-x1)*(x2-x1) + (y2-y1)*(y2-y1));
        }

        fn dist_pt_line_segment(x1: f32, y1: f32, x2: f32, y2: f32, x3: f32, y3: f32) -> f32 {
            // Distance of pt (x3,y3) to line segment (x1,y1) (x2,y2)
            //https://stackoverflow.com/questions/849211/shortest-distance-between-a-point-and-a-line-segment
            let px = x2-x1;
            let py = y2-y1;
            let norm = px*px + py*py;
            var u = ((x3 - x1) * px + (y3 - y1) * py) / norm;
            if u > 1.0 {
                u = 1.0;
                } else if u < 0.0 {
                u = 0.0;
                }
            let dx = x1 + u * px - x3;
            let dy = y1 + u * py - y3;
            return sqrt(dx*dx + dy*dy);
        }
```

**Comment by almarklein** [comment]
> Do you know the logic of how the distances are arranged?

```
    b
  2___3
  |   |
a |   | c
  |___|
  1 d 4
```

It's easiest to assign each one edge to each position. E.g. `vec4<f32>(dist_a, dist_b, dist_c, dist_d)`.

Then the set `wireframe_coord`  should be such that at the current vertex, zeros are set for the edges that intersect with that vertex. So in the below, for vertex 1 it should be `vec4<f32>(0.0, dist_b, dist_c, 0.0)`.

----

I found the missing piece! You also need to take the extra value into account when they are min-ned. In the fragment shader:
```py
            $$ if wireframe
                $$ if indexer == 3
                let distance_from_edge = min(varyings.wireframe_coords.x, min(varyings.wireframe_coords.y, varyings.wireframe_coords.z));
                $$ else
                let distance_from_edge = min(varyings.wireframe_coords.x, min(varyings.wireframe_coords.y, min(varyings.wireframe_coords.z, varyings.wireframe_coords.a)));
                $$ endif
                if (distance_from_edge > 0.5 * u_material.wireframe) {
                    discard;
                }
            $$ endif
```

This also fixes that some lines are thick while others are thin.

**Comment by sharon92** [comment]
@almarklein  that worked like a charm! Thanks a lot!
![image](https://github.com/pygfx/pygfx/assets/51754340/721649fc-1e11-441c-bda3-4c3f334a9768)

**Comment by Korijn** [comment]
Can we close this issue?
