### ISSUE TITLE
Strange Error

### ISSUE THREAD

**Issue by milen-prg** [pygfx/pygfx#594]
Windows 10 Pro 64bit, Python 3.11 all updated.

The simples example returns ERROR:

`import pygfx as gfx
import pylinalg as la

cube = gfx.Mesh(
    gfx.box_geometry(200, 200, 200),
    gfx.MeshPhongMaterial(color="#336699"),
)

rot = la.quat_from_euler((0, 0.01), order="XY")

def animate():
    cube.local.rotation = la.quat_mul(rot, cube.local.rotation)

if __name__ == "__main__":
    gfx.show(cube, before_render=animate)`

And the ERROR:

Exception ignored from cffi callback <function GPU.request_adapter.<locals>.callback at 0x000001E08304B240>:
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\wgpu\backends\rs.py", line 273, in callback
    raise RuntimeError(f"Request adapter failed ({status}): {msg}")
RuntimeError: Request adapter failed (1): NotFound
Traceback (most recent call last):
  File "C:\Users\mlap\Downloads\a.py", line 15, in <module>
    gfx.show(cube, before_render=animate)
  File "C:\Python311\Lib\site-packages\pygfx\utils\show.py", line 271, in show
    ).show(object, up)
      ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pygfx\utils\show.py", line 168, in show
    self.renderer = WgpuRenderer(self.canvas)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pygfx\renderers\wgpu\_renderer.py", line 136, in __init__
    self._shared = get_shared()
                   ^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pygfx\renderers\wgpu\_shared.py", line 151, in get_shared
    Shared()
  File "C:\Python311\Lib\site-packages\pygfx\renderers\wgpu\_shared.py", line 58, in __init__
    self._adapter = wgpu.request_adapter(
                    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\wgpu\backends\rs.py", line 282, in request_adapter
    assert adapter_id is not None
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by Korijn** [comment]
Can you check if your system has a GPU and if you've installed and updated GPU drivers?

**Comment by kushalkolar** [comment]
WGPU can utilize DX12 and Vulkan on Windows, you probably have to revert to an older driver to use DX12 on the HD 4400, see: https://www.intel.com/content/www/us/en/support/articles/000057520/graphics.html 

My guess is that it doesn't support Vulkan since it's pretty old, see the table here: https://www.intel.com/content/www/us/en/support/articles/000005524/graphics.html

**Comment by Korijn** [comment]
@almarklein this is actually a pretty good example of ehy assert's aren't great in user code :)

**Comment by milen-prg** [comment]
The DX12 works on my system and tests are good. The Vulkan is not supported, unfortunately.

😥

**Comment by Korijn** [comment]
You can try setting an environment variable `WGPU_BACKEND_TYPE` to `D3D12` and re-run pygfx.

**Comment by milen-prg** [comment]
> You can try setting an environment variable `WGPU_BACKEND_TYPE` to `D3D12` and re-run pygfx.

Oh, there is light in the tunnel!
The script start and work with thins environment variable!
BUT, after 2-3 seconds, again other ERROR:

Forcing backend: D3D12 (3)
Map buffer failed: 0x887A0005
Mapping failed Device(Lost)
Error during handling pointer_move event
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\wgpu\gui\base.py", line 23, in log_exception
    yield
  File "C:\Python311\Lib\site-packages\wgpu\gui\base.py", line 301, in handle_event
    callback(event)
  File "C:\Python311\Lib\site-packages\pygfx\renderers\wgpu\_renderer.py", line 771, in convert_event
    info = self.get_pick_info((event["x"], event["y"]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pygfx\renderers\wgpu\_renderer.py", line 675, in get_pick_info
    data = self._pixel_info_buffer.map_read()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\wgpu\backends\rs.py", line 1586, in map_read
    raise RuntimeError(f"Could not read buffer data ({status}).")
RuntimeError: Could not read buffer data (3).
Map buffer failed: 0x887A0005
Mapping failed Device(Lost)
Error during handling pointer_move event: Could not read buffer data … (2)
Buffer creation failed: 0x887A0005
thread '<unnamed>' panicked at 'Unable to write buffer: Queue(Lost)', src\device.rs:721:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


The Rust is not installed on my system.

**Comment by Korijn** [comment]
Well, you don't need to have Rust installed :)

Can you define the environment variable `RUST_BACKTRACE=1` as instructed and run again? That way we can see a little more detail and help debug.

**Comment by milen-prg** [comment]
I set RUST_BACKTRACE=full (recommendation of the next error message) and:

Forcing backend: D3D12 (3)
Map buffer failed: 0x887A0005
Mapping failed Device(Lost)
Error during handling pointer_move event
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\wgpu\gui\base.py", line 23, in log_exception
    yield
  File "C:\Python311\Lib\site-packages\wgpu\gui\base.py", line 301, in handle_event
    callback(event)
  File "C:\Python311\Lib\site-packages\pygfx\renderers\wgpu\_renderer.py", line 771, in convert_event
    info = self.get_pick_info((event["x"], event["y"]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pygfx\renderers\wgpu\_renderer.py", line 675, in get_pick_info
    data = self._pixel_info_buffer.map_read()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\wgpu\backends\rs.py", line 1586, in map_read
    raise RuntimeError(f"Could not read buffer data ({status}).")
RuntimeError: Could not read buffer data (3).
Buffer creation failed: 0x887A0005
thread '<unnamed>' panicked at 'Unable to write buffer: Queue(Lost)', src\device.rs:721:10
stack backtrace:
   0:     0x7ffa9f2a3352 - wgpu_render_pass_execute_bundles
   1:     0x7ffa9f2bb11b - wgpu_render_pass_execute_bundles
   2:     0x7ffa9f2a051a - wgpu_render_pass_execute_bundles
   3:     0x7ffa9f2a309b - wgpu_render_pass_execute_bundles
   4:     0x7ffa9f2a55e9 - wgpu_render_pass_execute_bundles
   5:     0x7ffa9f2a526a - wgpu_render_pass_execute_bundles
   6:     0x7ffa9f2a5e71 - wgpu_render_pass_execute_bundles
   7:     0x7ffa9f2a5bfd - wgpu_render_pass_execute_bundles
   8:     0x7ffa9f2a3d7f - wgpu_render_pass_execute_bundles
   9:     0x7ffa9f2a58c0 - wgpu_render_pass_execute_bundles
  10:     0x7ffa9f2e1d45 - wgpu_render_pass_execute_bundles
  11:     0x7ffa9f2e2053 - wgpu_render_pass_execute_bundles
  12:     0x7ffa9f02f66a - wgpuQueueWriteBuffer
  13:     0x7ffaa0a310f3 - <unknown>
  14:     0x7ffaa0a4aba0 - PyInit__cffi_backend
  15:     0x7ffaa0a373af - <unknown>
  16:     0x7ffaa0216438 - PyObject_MakeTpCall
  17:     0x7ffaa021a038 - PyObject_Vectorcall
  18:     0x7ffaa021b894 - PyEval_EvalFrameDefault
  19:     0x7ffaa02481ef - PyObject_GetBuffer
  20:     0x7ffaa036bdd1 - PyDict_Values
  21:     0x7ffaa0a158d3 - PyInit__asyncio
  22:     0x7ffaa0a15747 - PyInit__asyncio
  23:     0x7ffaa0a16023 - PyInit__asyncio
  24:     0x7ffaa0290f3c - PyIter_Send
  25:     0x7ffaa04549f9 - PyContext_NewHamtForTests
  26:     0x7ffaa0454cd9 - PyContext_NewHamtForTests
  27:     0x7ffaa028f5f0 - PyUnicode_RichCompare
  28:     0x7ffaa0292c4b - PyObject_Call
  29:     0x7ffaa02929be - PyList_AsTuple
  30:     0x7ffaa022018a - PyEval_EvalFrameDefault
  31:     0x7ffaa023dbc7 - PyMapping_Check
  32:     0x7ffaa023d287 - PyEval_EvalCode
  33:     0x7ffaa02bbae6 - PyUnicode_GetLength
  34:     0x7ffaa02bba62 - PyUnicode_GetLength
  35:     0x7ffaa03da432 - PyThread_tss_is_created
  36:     0x7ffaa0311081 - PyRun_SimpleFileObject
  37:     0x7ffaa02792cc - PyRun_AnyFileObject
  38:     0x7ffaa027979b - Py_MakePendingCalls
  39:     0x7ffaa027980b - Py_MakePendingCalls
  40:     0x7ffaa0279e84 - Py_RunMain
  41:     0x7ffaa0279d15 - Py_RunMain
  42:     0x7ffaa0307311 - Py_Main
  43:     0x7ff618491230 - <unknown>
  44:     0x7ffae5397344 - BaseThreadInitThunk
  45:     0x7ffae55026b1 - RtlUserThreadStart

**Comment by Korijn** [comment]
Yeah it will run for much longer if you don't move the mouse :)

 > Error during handling pointer_move event

**Comment by almarklein** [comment]
Perhaps we're using buffers in a way that's not supported by dx12? Will have to sit at a Windows box and see if I can reproduce this. For now I updated the title to reflect this specific error.

**Comment by milen-prg** [comment]
Yes, if I did not move the mouse over the script window, it works! I hope you to succeed to fix this problem for Windows. Thank you, very much!
