### ISSUE TITLE
View Flickering Glitch when running a scene

### ISSUE THREAD

**Issue by Sparsh-N** [pygfx/pygfx#633]
Greetings,

I've been using Pygfx to render few scenes, but a issue that's happened whenever I run any scene is that there's a dark spot/flickering effect that occurs when viewing/panning the view in full screen / any size larger than the original size of the canvas. I've attached a small gif below showing this glitch, where dark spots usually cover the rest of the view (This issue occurs across all scenes/objects, not just with the objects I've been using). This issue does not occur when it starts, only when it's opened in full screen/a larger canvas size.

![issuegithub](https://github.com/pygfx/pygfx/assets/107741753/c7e6c802-a4b5-4c0c-9ee3-35a7dbfee5e5)

My laptop has a RTX 3050 Ti Mobile GPU with Ryzen 7 5800U CPU, and I've observed that it uses the 3050 Ti when running the scene.
**Versions**
Graphics Driver (3050 Ti): 30.0.15.1274
Pyside6: pyside6-6.6.1
Wgpu: 0.13.1
Imageio: 2.19.3

**Comment by Korijn** [comment]
Can you share minimal example code to reproduce?

**Comment by Sparsh-N** [comment]
Here's the code I used for running the scene: 
```
import numpy as np
from wgpu.gui.auto import WgpuCanvas, run
import pygfx as gfx

canvas = WgpuCanvas()
renderer = gfx.renderers.WgpuRenderer(canvas)
scene = gfx.Scene()

# 3D Line based approach -> LineSegmentMaterial
# Single Span, from 0 -> 100, 2 vertices

def create(x, y, z):
    positions = np.column_stack([x, y, z])
    line = gfx.Line(
        gfx.Geometry(positions=positions, colors=[(0, 1, 1, 1)]),
        gfx.LineThinMaterial(thickness=1.0)
    )
    return line

x = np.linspace(20, 980, 200, dtype=np.float32)
y = np.sin(x / 30) * 4

positions = np.column_stack([x, y, np.zeros_like(x)])
colors = np.random.uniform(0, 1, (x.size, 4)).astype(np.float32)
colors[:, 3] = 1

for i in range(200):
    line = create(x, y + i + 100, np.zeros_like(x) + i)
    scene.add(line)

camera = gfx.OrthographicCamera(maintain_aspect=False)
camera.show_rect(0, 1000, -5, 5)    

camera = gfx.OrthographicCamera(100, 16 / 9)
camera.local.position = (100, 100, 50)
camera.show_pos((0, 0, 0))
controller = gfx.OrbitController(camera, register_events=renderer)

if __name__ == "__main__":
    canvas.request_draw(lambda: renderer.render(scene, camera))
    run()
```

**Comment by almarklein** [comment]
You don't mean the Moiré efect of the lines, right? In the gif it looks like part of the object is suddenly not drawn anymore. This looks a bit like a depth buffer issue on first sight, but I cannot reproduce it with the given code (thanks for that btw).

What OS are you on?

**Comment by Sparsh-N** [comment]
Hi Almar,

I'm not looking towards the moire issues, mostly focused on the flickering. I think you're right that depth buffer issues may be the cause. I'm using Windows 11. I tried updating my graphics drivers to the most recent one available, although now none of the scenes using pygfx/wgpu run. I've attached a short gif below which shows this issue on one of the introduction scenes, recorded before I updated drivers:

![Demo](https://github.com/pygfx/pygfx/assets/107741753/579adb2d-d230-475f-aa74-58c3291ee4a2)

**Comment by almarklein** [comment]
That looks really strange. Since the glitch seems to happen in blocks, and the fragments on the blue box and background seem to be affected equally, I don't think this is related to the depth buffer after all.

> I tried updating my graphics drivers to the most recent one available, although now none of the scenes using pygfx/wgpu run.

Oh, that's annoying! In what way does it not-work now? Does it crash and is there an error of some kind?

You could try `pip install glfw`, so the examples run on GLFW instead of PySide, so we can exclude that Qt is at fault.

**Comment by Sparsh-N** [comment]
Thanks for the suggestions Almar, I've been running with glfw since the start due to some issue with my Qt installation. Initially, it just crashed with a mention that "Qt couldn't be found", although this error also popped up when opening the Radeon Software for my iGPU.

I've found a fix for at least part of this issue. I noticed that when I disable either of the Display Adapters (The integrated GPU // 3050Ti) in the Device Manager, all of the issues seem to get fixed (Running in GLFW, with the newer 3050Ti Driver also works), so it may just be a issue with GLFW not knowing which Display Driver to use when 2 are available.

**Comment by Sparsh-N** [comment]
I'm not sure if I should reopen this issue, as I don't have any other way to test it/replicate the glitch on another device with 2 display adapters. That being said, having to switch display adapters off each time I want to run a scene might not be the best solution, so I'll look into whether this is a issue with the drivers or with GLFW.

**Comment by almarklein** [comment]
Could you try running `gfx.print_wgpu_report()`. Mostly interested in the adapter info section. (It may raise an error because we did not yet update it to the new wgpu diagnostic mechanism, but only printing the info of interest.)

**Comment by Sparsh-N** [comment]
Here's the adapter section, there is a traceback error but whenever I run `gfx.print_wgpu_report()` after the `run()` call, it allows me to pan around the scene without any issues, and only comes after I close it. When called before run, it automatically closes. I've tried running it with both GPU enabled, although the window still freezes/pauses whenever I attempt to print the report.

Adapter Section for integrated GPU:
```
ADAPTER INFO:
                                            vendor: AMD proprietary driver
                                      architecture: 
                                            device: AMD Radeon(TM) Graphics
                                       description: 20.40.52
                                      adapter_type: IntegratedGPU
                                      backend_type: Vulkan

FEATURES:                                             adapter     device
                               bgra8unorm-storage:          -          -
                            depth32float-stencil8:          Y          -
                               depth-clip-control:          Y          -
                               float32-filterable:          -          -
                          indirect-first-instance:          Y          -
                         rg11b10ufloat-renderable:          Y          -
                                       shader-f16:          Y          -
                         texture-compression-astc:          -          -
                           texture-compression-bc:          Y          -
                         texture-compression-etc2:          -          -
                                  timestamp-query:          Y          -
                                MultiDrawIndirect:          Y          -
                           MultiDrawIndirectCount:          Y          -
                                    PushConstants:          Y          -
             TextureAdapterSpecificFormatFeatures:          Y          Y
                            VertexWritableStorage:          Y          -

LIMITS:                                               adapter     device
                                  max_bind_groups:          8          8
              max_bind_groups_plus_vertex_buffers:          0          0
                      max_bindings_per_bind_group:       1000       1000
                                  max_buffer_size: 18446744073709551615  268435456
            max_color_attachment_bytes_per_sample:          0          0
                            max_color_attachments:          0          0
            max_compute_invocations_per_workgroup:       1024       1024
                     max_compute_workgroup_size_x:       1024       1024
                     max_compute_workgroup_size_y:       1024       1024
                     max_compute_workgroup_size_z:       1024       1024
               max_compute_workgroup_storage_size:      65536      65536
             max_compute_workgroups_per_dimension:      65535      65535
  max_dynamic_storage_buffers_per_pipeline_layout:          8          8
  max_dynamic_uniform_buffers_per_pipeline_layout:          8          8
                max_inter_stage_shader_components:        128        128
                 max_inter_stage_shader_variables:          0          0
            max_sampled_textures_per_shader_stage: 4294967295         16
                    max_samplers_per_shader_stage: 4294967295         16
                  max_storage_buffer_binding_size: 2147483648 2147483648
             max_storage_buffers_per_shader_stage: 4294967295          8
            max_storage_textures_per_shader_stage: 4294967295          4
                         max_texture_array_layers:       2048       2048
                          max_texture_dimension1d:      16384      16384
                          max_texture_dimension2d:      16384      16384
                          max_texture_dimension3d:       2048       2048
                  max_uniform_buffer_binding_size: 2147483648 2147483648
             max_uniform_buffers_per_shader_stage: 4294967295         12
                            max_vertex_attributes:         64         64
                   max_vertex_buffer_array_stride:      16383      16383
                               max_vertex_buffers:         16         16
              min_storage_buffer_offset_alignment:         32         32
              min_uniform_buffer_offset_alignment:         32         32

CACHES:                   Count       Hits     Misses
   full_quad_objects          0          0          0
    mipmap_pipelines          0          0          0
             layouts          0          0          0
            bindings          0          0          0
      shader_modules          0          0          0
           pipelines          0          0          0
    shadow_pipelines          0          0          0

RESOURCES:                Count
            Texture:          6
             Buffer:       2004

Traceback (most recent call last):
  File "c:\Users\Sparsh N\fury\fury\wgpu\window.py", line 50, in <module>
    gfx.print_wgpu_report()
  File "C:\Users\Sparsh N\anaconda3\lib\site-packages\pygfx\renderers\wgpu\_shared.py", line 199, in print_wgpu_report     
    wgpu.print_report()
AttributeError: module 'wgpu' has no attribute 'print_report'
``` 

When I run it using my dGPU (RTX 3050 Ti), here is the output. The traceback error is same, although the GL context message is new:
```
Returned GL context is 1.1, when 3.3+ is needed

ADAPTER INFO:
                                            vendor: NVIDIA
                                      architecture:
                                            device: NVIDIA GeForce RTX 3050 Ti Laptop GPU
                                       description: 512.74
                                      adapter_type: DiscreteGPU
                                      backend_type: Vulkan

FEATURES:                                             adapter     device
                               bgra8unorm-storage:          -          -
                            depth32float-stencil8:          Y          -
                               depth-clip-control:          Y          -
                               float32-filterable:          -          -
                          indirect-first-instance:          Y          -
                         rg11b10ufloat-renderable:          Y          -
                                       shader-f16:          Y          -
                         texture-compression-astc:          -          -
                           texture-compression-bc:          Y          -
                         texture-compression-etc2:          -          -
                                  timestamp-query:          Y          -
                                MultiDrawIndirect:          Y          -
                           MultiDrawIndirectCount:          Y          -
                                    PushConstants:          Y          -
             TextureAdapterSpecificFormatFeatures:          Y          Y
                            VertexWritableStorage:          Y          -

LIMITS:                                               adapter     device
                                  max_bind_groups:          8          8
              max_bind_groups_plus_vertex_buffers:          0          0
                      max_bindings_per_bind_group:       1000       1000
                                  max_buffer_size: 18446744073709551615  268435456
            max_color_attachment_bytes_per_sample:          0          0
                            max_color_attachments:          0          0
            max_compute_invocations_per_workgroup:       1024       1024
                     max_compute_workgroup_size_x:       1024       1024
                     max_compute_workgroup_size_y:       1024       1024
                     max_compute_workgroup_size_z:         64         64
               max_compute_workgroup_storage_size:      49152      49152
             max_compute_workgroups_per_dimension:      65535      65535
  max_dynamic_storage_buffers_per_pipeline_layout:         16         16
  max_dynamic_uniform_buffers_per_pipeline_layout:         15         15
                max_inter_stage_shader_components:        128        128
                 max_inter_stage_shader_variables:          0          0
            max_sampled_textures_per_shader_stage:    1048576    1048576
                    max_samplers_per_shader_stage:    1048576    1048576
                  max_storage_buffer_binding_size: 2147483648 2147483648
             max_storage_buffers_per_shader_stage:    1048576    1048576
            max_storage_textures_per_shader_stage:    1048576    1048576
                         max_texture_array_layers:       2048       2048
                          max_texture_dimension1d:      32768      32768
                          max_texture_dimension2d:      32768      32768
                          max_texture_dimension3d:      16384      16384
                  max_uniform_buffer_binding_size:      65536      65536
             max_uniform_buffers_per_shader_stage:    1048576    1048576
                            max_vertex_attributes:         32         32
                   max_vertex_buffer_array_stride:       2048       2048
                               max_vertex_buffers:         16         16
              min_storage_buffer_offset_alignment:         32         32
              min_uniform_buffer_offset_alignment:         64         64

CACHES:                   Count       Hits     Misses
   full_quad_objects          1          0          2
    mipmap_pipelines          0          0          0
             layouts          1        499        501
            bindings        500          0        500
      shader_modules          1        499          1
           pipelines        500          0        500
    shadow_pipelines          0          0          0

RESOURCES:                Count
            Texture:          6
             Buffer:       2505
```

**Comment by Sparsh-N** [comment]
Hi Almar, sorry for the delay but I've gotten back to using pygfx. In terms of the adapters, running the scene was relatively sluggish using the dGPU compared to the iGPU, and it also had more cache misses.

**Comment by almarklein** [comment]
In your previous comment you wrote:

> I've tried running it with both GPU enabled, although the window still freezes/pauses whenever I attempt to print the report.

Are you saying you cannot print the report when both GPU's are enabled? I was interested mostly in what adapter is selected when both GPU's are enabled, as it may point to an error in the adapter selection logic in wgpu-core.
