### ISSUE TITLE
Performance Problems with Large Numbers of Meshes

### ISSUE THREAD

**Issue by lnargang** [pygfx/pygfx#634]
Hello!
I am trying to create a program and running into some problems that are related to a need for a large number (1000+) of meshes, but I am running into problems as minor as bad framerates and as bad as crashes on load. I had some questions about how pygfx handles some systems so I can better understand how I can achieve the needed outcome.

I know for larger numbers of meshes, there is the InstancedMesh object, which on the surface seems to be what I am looking for, but I would like to be able to have both a large number and also a pickable large number, and I am unclear on how an InstancedMesh handles picking, and if the individual parts can be picked independently? 
Also, is it possible to mimic InstancedMesh functionality but with larger numbers of more uniquely shaped meshes?

Otherwise, is there any more advice about achieving large numbers of rendered objects in pygfx, and other functionality that I haven't considered? Any help would be appreciated. 

Thank you so much!

**Comment by Korijn** [comment]
Thanks for reporting!

Can you provide minimal example code to reproduce your problems?

Can you give more detail regarding your use case? E.g. are all the meshes identical? Are they all visible at the same time?

**Comment by sharon92** [comment]
I had the same issue with rendering 3000+ Line Objects. @almarklein mentioned that behind the scenes pygfx loops through objects inefficiently and it is something to be improved in the future.

My solution was to merge all the lines in a single object by using nan values to seperate different lines. This improved the frame rate significantly.

Perhaps you can merge your meshes in a similar way?

**Comment by Korijn** [comment]
I feel like we should write a separate document about performance.

In general, any 3D rendering engine will have trouble with large amount of objects in the scene. This is **not** a challenge specific to pygfx.

In order to address this issue, there are two types of things you can do. Limit the amount of objects on the screen (1), and push as much rendering work from the CPU to the GPU (2).

Some examples:

* visibility culling (1) (not available in pygfx)
* rendering distance (1) (not available in pygfx)
* dynamic level of detail meshes (1) (not available in pygfx)
* instancing (2) (available in pygfx)
* batching (2) (available in pygfx, as @sharon92 explained)

However, even with all these improvements, you can still find that there are performance problems with giant amounts of objects and triangles to render. This is natural. Your computer cannot perform infinite amount of work instantly. :)

**Comment by mikeny07** [comment]
The most efficient way to handle large number of meshes or large particle systems is to use compute shader in WebGPU. Here is an [example](https://piellardj.github.io/water-webgpu/?page%3Atabs%3Arender-mode-tabs-id=4&page%3Atabs%3Aparticles-radius-tabs-id=0.005&page%3Aselect%3Aparticles-quantity-select-id=xxx) of a water simulation with 492,719 particles:
I can still get a 60 FPS. This is impossible without using compute shader. Does the pygfx engine allow to compute shaders?

**Comment by Korijn** [comment]
Well, yes, but how exactly are you going to render triangle meshes with a compute shader?

**Comment by mikeny07** [comment]
Just create the vertex data directly using compute shaders. Here is a direct comparison using CPU and GPU (compute shader) to create a procedural terrain. To animate the terrain, we need to update the vertex data for every frame. Using CPU, you get a 3 FPS for a resolution of 500 by 500 grid (see the [demo](https://webgpu-gpu-book.drxudotnet.com/#ch08-terrain-animation). However, using compute shader we can still get a  60 FPS even for a 2048 by 2048 grid (see the[ demo](https://webgpu-gpu-book.drxudotnet.com/#ch08-terrain-gpu))

**Comment by Korijn** [comment]
Well sure, but in all the problems you are referencing the bottleneck is animation (updating the vertex data). Rendering is not the bottleneck in the examples you're referencing.

**Comment by mikeny07** [comment]
In WebGPU, rendering large system IS the bottleneck. In general, rendering a large number of meshes of a 3D object can be more efficient when creating the vertex data directly on the GPU (for rendering only, even not for animation) using a compute shader compared to creating the vertex data on the CPU using JavaScript (or Python in the pygfx engine). This is because of the parallel processing capabilities of the GPU and the reduced need for data transfer between the CPU and GPU.

Here are some key reasons why GPU-based computation can be faster in this context:

- Parallelism: compute shaders or GPUs are designed to handle massive parallelism, with hundreds or thousands of processing cores. A compute shader can perform computations on each vertex independently and concurrently, taking advantage of the parallel processing power of the GPU. This is in contrast to JavaScript or Python running on the CPU, which typically executes instructions sequentially.

- Data Transfer Overhead: When creating vertex data on the CPU, the data needs to be transferred from the CPU to the GPU (the rendering shader) memory before rendering. This involves moving large amounts of data over the bus between the CPU and GPU, which can introduce latency and reduce performance. By generating vertex data directly on the GPU using a compute shader, you eliminate the need for this data transfer, resulting in faster rendering.

This is why game engines like Unity use compute shaders to generate vertex data for creating terrains or complex 3D objects.

**Comment by Korijn** [comment]
I'm sorry but you are really missing the point. Vertex data only needs to be uploaded to the GPU when it has been created, and when it is modified. When you are rendering a 1000+ **static** meshes, the vertex data is uploaded to the GPU only once at the start of your program.

After that you start rendering that data to the screen at some framerate. If there are too many meshes and triangles, you will have poor performance. There is no way compute shaders will help in this scenario.

**Comment by Korijn** [comment]
Here's an example of poor performance as OP has described:

```py
from wgpu.gui.auto import WgpuCanvas, run
import pygfx as gfx


canvas = WgpuCanvas()
renderer = gfx.renderers.WgpuRenderer(canvas)
scene = gfx.Scene()

geometry = gfx.torus_knot_geometry(1, 0.3, 2**10, 2**6)
material = gfx.MeshPhongMaterial()

N = 1000
for i in range(N):
    obj = gfx.Mesh(geometry, material)
    obj.local.x = i - N/2
    scene.add(obj)

camera = gfx.PerspectiveCamera(70, 1)
camera.show_object(scene)

scene.add(gfx.AmbientLight(), camera.add(gfx.DirectionalLight()))

controller = gfx.OrbitController(camera, register_events=renderer)


if __name__ == "__main__":
    canvas.request_draw(lambda: renderer.render(scene, camera))
    run()
```

The most straight forward solution here is to use InstancedMesh.

**Comment by Korijn** [comment]
>  I am unclear on how an InstancedMesh handles picking, and if the individual parts can be picked independently?

Here's how to do it (I've combined `examples/feature_demo/instancing_mesh.py` and `examples/feature_demo/picking_mesh.py`):

```py
import numpy as np
import imageio.v3 as iio
from wgpu.gui.auto import WgpuCanvas, run
import pygfx as gfx
import pylinalg as la


canvas = WgpuCanvas()
renderer = gfx.renderers.WgpuRenderer(canvas)
scene = gfx.Scene()

im = iio.imread("imageio:bricks.jpg").astype(np.float32) / 255
tex = gfx.Texture(im, dim=2)

geometry = gfx.torus_knot_geometry(1, 0.3, 128, 32)
geometry.texcoords.data[:, 0] *= 10  # stretch the texture
material = gfx.MeshPhongMaterial(map=tex)
obj = gfx.InstancedMesh(geometry, material, 100)
scene.add(obj)


# Set matrices. Note that these are sub-transforms of the mesh's own matrix.
for y in range(10):
    for x in range(10):
        m = la.mat_from_translation((y * 2, x * 2, 0))
        obj.set_matrix_at(x + y * 10, m)


camera = gfx.PerspectiveCamera(70, 1)
camera.local.position = (9, 9, 15)

scene.add(gfx.AmbientLight())
scene.add(camera.add(gfx.DirectionalLight()))


def on_pick(event):
    info = event.pick_info
    print(info['instance_index'])


obj.add_event_handler(on_pick, "pointer_down")

def animate():
    rot = la.quat_from_euler((0.0071, 0.01), order="XY")
    obj.local.rotation = la.quat_mul(rot, obj.local.rotation)

    renderer.render(scene, camera)
    canvas.request_draw()


if __name__ == "__main__":
    canvas.request_draw(animate)
    run()
```

> Also, is it possible to mimic InstancedMesh functionality but with larger numbers of more uniquely shaped meshes?

No, instancing is specifically intended to render multiple instances of the same mesh.

**Comment by lnargang** [comment]
Thank you for all your help with this, and apologies for my delay in following up. I understand how to use instanced meshes now, but I have one question. I am running into the limit on objects, and looking into the error it's due to the limit on claimable IDs. I am having trouble understanding their usage within InstancedMesh. Does an InstancedMesh claim IDs for every part of the mesh? Thanks in advance.

On another note, I'm running into a bug with the larger scale mesh. Here's some code:
`
import pygfx as gfx
import wgpu
from wgpu.gui.auto import WgpuCanvas, run
import pylinalg as la
import numpy as np

canvas = WgpuCanvas(size=(640,480))
renderer = gfx.WgpuRenderer(canvas)
scene = gfx.Scene()

geometry = gfx.box_geometry(1.0,1.0,1.0)

instanced_mesh = gfx.InstancedMesh(geometry, gfx.MeshPhongMaterial(), 10000)

for y in range(100):
    for x in range(100):
        m = la.mat_from_translation((y * 2, x * 2, 0))
        instanced_mesh.set_matrix_at(x + y * 100, m)

scene.add(instanced_mesh)

camera = gfx.PerspectiveCamera(45, 16 / 9)
camera.show_object(scene)
controller = gfx.OrbitController(camera=camera, enabled=True, register_events=renderer)

scene.add(gfx.AmbientLight())
scene.add(camera.add(gfx.DirectionalLight()))

def animate():
    renderer.render(scene=scene, camera=camera)
    canvas.request_draw()

if __name__ == "__main__":
    canvas.request_draw(animate)
    run()
`

When running the following, it properly creates an InstancedMesh with 10,000 cubes. However, something that seems problematic happens when zooming in. To reproduce:
![Screenshot 2024-01-16 220954](https://github.com/pygfx/pygfx/assets/64860683/009b38a9-656e-4bbf-b494-ead5cd109f95)

And then when you zoom in it causes this to occur:
![Screenshot 2024-01-16 220944](https://github.com/pygfx/pygfx/assets/64860683/4536f31f-c374-4132-a481-23153a2c53c4)

Is this known behavior?

Again, thank you for your help.

**Comment by almarklein** [comment]
> I am running into the limit on objects, and looking into the error it's due to the limit on claimable IDs.

How is this expressed, is there an error message?

> However, something that seems problematic happens when zooming in. To reproduce, view the mesh at an angle such as so:

By default the camera gets it near and far plane set by the controller. This makes sense, because the controller settings are often a good indication of the scale that must be visualized. However, this breaks down when zooming in on a large scene like this. So in this case it's better to explicitly set the `camera.depth_range` e.g. 
```py
camera.depth_range = 0.01, 100000
```

**Comment by lnargang** [comment]
Thanks for the info on how to limit the range of the camera. 

For the object limit, the output appears as follows:
```
Traceback (most recent call last):
  File "c:\Users\-\-\-\wgpu\instanced_mesh.py", line 13, in <module>
    instanced_mesh = gfx.InstancedMesh(geometry, gfx.MeshPhongMaterial(), 1000000)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\anaconda3\Lib\site-packages\pygfx\objects\_instanced.py", line 43, in __init__
    id = id_provider.claim_id(self)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\-\anaconda3\Lib\site-packages\pygfx\objects\_base.py", line 54, in claim_id
    raise RuntimeError("Max number of objects reached.")
RuntimeError: Max number of objects reached.
```

**Comment by almarklein** [comment]
Ah, right. We indeed limit the number of objects to 1 million. An instanced mesh consumes one id per instance, so that the instances themselves are pickable.

Unfortunately, the max is actually 999999 because we check for `>=max_items` instead of `>max_items` 😆.  We should change that, and perhaps provide a better error message.

**Comment by panxinmiao** [comment]
To be honest, there are a lot of work to be done for performance optimization in pygfx. It's difficult to explain everything in just one or two posts.

Many of our current solutions completely ignore performance issues.
For instance, **we have completely abandoned VertexBuffer and IndexBuffer**, and instead use StorageBuffer as a replacement.

First of all, the access speed of StorageBuffer itself is much lower than VertexBuffer, and we have also abandoned draw_indexed, which results in **the vertex shader actually processing far more vertices than the actual number of vertices**.
Our typical code for fetching vertex data in the vertex shader is as follows:

```wgsl
let index = i32(vertex_index);
let face_index = index / {{indexer}};
var sub_index = index % {{indexer}};
let vii = load_s_indices(face_index);
let i0 = i32(vii[sub_index]);
var raw_pos = load_s_positions(i0);
var raw_normal = load_s_normals(i0);
```
Consider a case with 4 vertices and 4 faces, assuming the vertex indices are `((0,1,2),(0,2,3),(0,3,1),(1,2,3))`. Normally (using draw_indexed), the vertex shader only needs to process 4 vertices, but we are actually processing 12 (because in the above code, `i0` is the actual vertex index, while `vertex_index` is the index of the vertex indices).
Moreover, we need to perform multiple StorageBuffer reads in the vertex shader to obtain the actual vertex data (position, normal), and the long **data dependency** prevents the compiler from performing any optimization, for example,  `raw_pos = load_s_positions(i0)` depends on the result of `load_s_indices(face_index)`, so it has to wait until the first StorageBuffer (indices) access is finished, making it impossible to perform parallel optimization.

All of the above may not have a noticeable impact when the number of vertices in the scene is not very large, but when the number of vertices is relatively large, the performance is extremely poor.

Additionally, there are too many unnecessary computations in our shaders.

There is a best practice principle for rendering engine optimization: **"move computations as early as possible"**.

- If something can be processed and calculated during the **Resource Preparation Stage**, calculate it in the **Resource Preparation Stage**.

- If something can be calculated during the **Render Preparation Stage** (the CPU stage before submitting draw calls to the GPU for each frame rendering), calculate it on the CPU during the **Render Preparation Stage**.

- Only if it is absolutely necessary to calculate in the **Shader Stage**, then calculate in the shader, and if it can be calculated in the vertex shader, calculate it in the vertex shader as much as possible.

This is because the fragment shader is per-pixel (or even per-sample, due to the existence of multi-sampling), while the vertex shader is per-vertex. Generally speaking, the number of pixels (samples) is much larger than the number of vertices, so **the computation in the fragment shader is more expensive than in the vertex shader, and the computation in the vertex shader is more expensive than a one-time computation on the CPU.**

For example, in our color space transformation, we use the `srgb2physical` method in the shader to process colors, which happens on every pixel of every frame rendered. However, we can completely calculate this only once on the CPU during the "**Resource Preparation Stage**".

Another example is the calculation of ndc_pos in the vertex shader. We upload the camera's projection matrix `projection_transform` and the camera transformation matrix `cam_transform_inv` to the shader, and then apply `projection_transform * cam_transform_inv * world_pos` on each vertex. However, we only need to pre-calculate `view_transform = projection_transform * cam_transform_inv` on the CPU during the "**Render Preparation Stage**" and pass it to the shader, then each vertex only needs to use `view_transform * world_pos`, reducing one matrix calculation. The calculation of `normal_matrix` and others also do not need to be performed in the shader, but can be calculated **once per frame during the "Render Preparation Stage"**.

The above is just part of the optimization related to shaders.
During the "render preparation stage" (the CPU stage before submitting draw calls to the GPU for each frame rendering), there are actually many other areas that can be optimized, such as frustum culling, Z-order sorting (to maximize the use of modern GPU's Early-Z capability), etc. We currently have a lot of "overdraws"

To be honest, There are many (in my opinion) somewhat strange designs in pygfx, such as using very complex logic in shaders to implement certain specific functions, even affecting the overall engine architecture, which in my opinion is somewhat not worth the effort.

For example, PointsShader and LineShader, the graphics API itself allows you to set primitive.topology to “point, line or triangle”, which is the geometric concept of GPU rendering. A point is a point, without size, only position, and a line is a line, without width. 
I understand that we want "points with size" or "lines with width", but these concepts of "points" or "lines" are higher-level concepts (perhaps at the application layer?). For GPU rendering (or the corresponding rendering engine), their geometric concept is a “triangle mesh”, and what our engine needs to do is to treat them as "triangle meshes", not "points" or "lines". This needs to be done during the **Resource Preparation Stage**, not the shader stage.

So, I think the rendering part of the engine doesn't need to care about these issues (points with size, lines with width) at all, it only cares about rendering itself. These should be implemented at a higher level (by constructing corresponding data structures, etc. to express these higher-level concepts). For example, a "point with size" is actually a sphere, which can be implemented through `InstancedMesh`, or `Sprites`, etc.
Taking a step back, even if we want to implement it the way the current shader does (using 6 vertices to represent 1 actual point), we should still generate and prepare this vertex data (6 times more) during the **Resource Preparation Stage** (one-time), rather than generating it in the shader every frame.


I'm sorry, I'm not entirely sure if some of the meanings are expressed clearly enough, :sweat_smile:

**Comment by almarklein** [comment]
Thanks for writing this up! I think you make some good points. Though I also think there is a mismatch in expectations about what pygfx is, which results in confusion related to some decisions we've made.

BTW: we're very excited and grateful for your contributions that add these more game-like rendering techniques like lights, shadows, environment maps, skinning! ❤️  

Our background is not games / simulation, but dataviz and medical visualizations. Our goal with pygfx is to build a versatile render engine that is also suited for scientific visualizations, ranging from plotting to 3D rendering. So, although we do cover the more classic game-like rendering, it's not the only goal. In the readme it says *pygfx emphasizes on hackability and correctness while maintaining the level of performance you would expect from a GPU accelerated library.* So, although we do care about performance, it's not the primary thing we optimize for. Sometimes maintainability / flexibility are more important. At least at this stage.

The points and line objects are a good example. These are primitives that are crucial for plotting, as well as annotations in scientific applications. I understand that they may feel "high-level", but from the p.o.v. of e.g. the `fastplotlib` team they very much feel like primitives.   

From users in the scientific domain, we keep hearing that pygfx performs much faster than other tools. So we feel we're on the right track 😄 

That said, it could very well be that along the way we've sacrificed performance for the more general case of triangle meshes. At least compared to render engines that really focus on these. Though I think there's room for optimizations to get good performance in more use-cases. 

----

> For instance, we have completely abandoned VertexBuffer and IndexBuffer, and instead use StorageBuffer as a replacement.

Yes. This approach is a crucial element in some shaders. And we've applied it also for the mesh shader for simplicity and consistency.

>  the access speed of StorageBuffer itself is much lower than VertexBuffer

From what I've read this is not the case for modern hardware, and I was also not able to detect a difference in performance at the time. That said, it could be that in e.g. very large meshes it becomes more noticeable.

I'm very much open for implementing more performant code-paths where it matters. Another idea (still untested) is to use a compute shader as a geometry pass. We would need a set of benchmarks first to be able to make informed decisions.


 > For example, in our color space transformation, we use the srgb2physical method in the shader to process colors, which happens on every pixel of every frame rendered.

I don't think that function is very expensive is it? The reason why its in the fragment shader, is because the color can be uniform, but it can also be per-vertex, per-face or looked up in a colormap. So the shader always obtains the final color, and *then* uses `srgb2physical`. We could optimize when the color is uniform, but that would increase complexity for a (I suspect) marginal gain.

> Another example is the calculation of ndc_pos in the vertex shader. We upload the camera's projection matrix projection_transform and the camera transformation matrix cam_transform_inv to the shader, and then apply projection_transform * cam_transform_inv * world_pos on each vertex. 

Good point! The reason why we have the separate matrices is that many shaders need them. I agree that we can also include the combined matrix and use that in the shaders where its possible. 👍 

> For GPU rendering (or the corresponding rendering engine), they are not "points" or "lines", their geometric concept is a “triangle mesh”, and what our engine needs to do is to treat them as "triangle meshes", not "points" or "lines". 

This is where I disagree. A lot of data does not convert to a triangle mesh so easily. If you look at the implementation of volume rendering or thick lines in e.g. ThreeJS, you see how awkward it is, and visually wrong in some cases (e.g. dashing). By making it a primitive in pygfx, we can implement these objects *much* better. 

Or the new grid primitive in #743, good luck creating a grid with such good properties using triangle meshes 😅 

> For example, a "point with size" is actually a sphere, which can be implemented through InstancedMesh, or Sprites, etc.

The Points are indeed *very* much like a sprite implementation, but aimed specifically for predefined markers. The downside of instancing is that the number of points would then be limited for some drivers/hardware. The current implementation handles millions of points with ease.

Calculating vertex positions (for billboarding) in the shader results in *much* faster visualizations than if that would have to be done on the CPU in a resource preparation stage. This is especially the case in Python, but would probably be true for static languages as well.

**Comment by Korijn** [comment]
I am getting the impression chatgpt is generating (a portion of) this feedback. Is this true @panxinmiao?

Taking the feedback on lines and points as an example, it's clear that the usecase and context is ignored in the argument for performance.

Of course, if a line is static, generating the triangle mesh once and then rendering that mesh on every frame with an optimized shader will be much more performant than our implementation.

But our implementation is an incredible state of the art shader than can generate the geometry on the fly! It allows you to change the geometry of the line, and its aesthetics, in real time every single frame! How exactly is this a bad thing? Not even unreal engine is capable of this AFAIK.

**Comment by panxinmiao** [comment]
> I am getting the impression chatgpt is generating (a portion of) this feedback. Is this true @panxinmiao?
> 
My native language is not English, so I used some translation tools to complete it. 😅 

> Taking the feedback on lines and points as an example, it's clear that the usecase and context is ignored in the argument for performance.

> Of course, if a line is static, generating the triangle mesh once and then rendering that mesh on every frame with an optimized shader will be much more performant than our implementation.

Let's clarify first:
The **Resource Preparation Stage** only needs to be executed once during the entire application.
The **Render Preparation Stage** is executed once before each frame rendering (on the CPU, or executed only once on the compute shader), without the need to execute on every vertex or every pixel like in the vertex or fragment shaders.

I think that even if we use the current PointShader logic, we should try to prepare as much data as possible in the **Resource Preparation Stage**.

For example, the "position" buffer can directly generate 6 times the number of vertices (at least we can simply copy each vertex 6 times), and the same applies to "vertex colors" and "vertex sizes". Then, input them using VertexBuffer. At the very least, we no longer need to access the StorageBuffer multiple times in the vertex shader (and due to data dependencies, access to the StorageBuffer must be serial). This will definitely improve performance. I'm not sure if there are other data needed in the shaders that can be prepared in the **Resource Preparation Stage**. If so, my suggestion is to calculate them first in the **Resource Preparation Stage**, and then input them all at once using VertexBuffer.


> I don't think that function is very expensive is it? The reason why its in the fragment shader, is because the color can be uniform, but it can also be per-vertex, per-face or looked up in a colormap. So the shader always obtains the final color, and then uses srgb2physical.

The same applies to color space conversion, whether it's uniform color, vertex color, or color from texture sampling, they can all be converted in advance in the **Resource Preparation Stage**.
_(We discussed before that, theoretically speaking, sampling first (interpolation occurs in the sRGB space) and then converting the color space is not entirely correct. unorm textures can use the -srgb format for direct conversion, and other textures can also be converted in one go.)_

The calculation from sRGB to physical space is indeed not very expensive, but this is just a typical example that should be completed in the resource preparation stage instead of being calculated every frame and every pixel in the fragment shader. I think the performance loss is the accumulation of all these small problems.

**Comment by almarklein** [comment]
> For example, the "position" buffer can directly generate 6 times the number of vertices (at least we can simply copy each vertex 6 times)

The positions must be calculated in the shader, because they depend on the camera view. But sure, we can copy all vertex data 6 times, so that we can use vertex buffers and avoid sampling the storage buffer. But in that case, the data size is increased 6-fold (!), so I'm not convinced that it would be any faster. Again, benchmarks would be needed.

For lines, we cannot apply this trick, because it needs access to the next and previous vertex. So it'd mean having different code paths and added complexity. We could do research to see whether its worth it (for specific use-cases) but right now there many other tasks with higher priority :)

> The same applies to color space conversion, whether it's uniform color, vertex color, or color from texture sampling, they can all be converted in advance in the Resource Preparation Stage. [...] and then converting the color space is not entirely correct.

The implementation is this:
```wgsl
fn srgb2physical(color: vec3<f32>) -> vec3<f32> {
    // In Python, the below reads as
    // c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4
    let f = pow((color + 0.055) / 1.055, vec3<f32>(2.4));
    let t = color / 12.92;
    return select(f, t, color <= vec3<f32>(0.04045));
    // Simplified version with about 0.5% avg error
    // return pow(color, vec3<f32>(2.2));
}
```

Not a whole lot of code. I simply don't thing that sacrificing correctness and simplicity (just convert at the end of the frag shader) are worth such a marginal performance gain. I'd rather use the commented simplified version -- if the gain is significant. Should be easy to do some tests to see if it improves performance.

> I think the performance loss is the accumulation of all these small problems.

What performance loss do you mean here? Loss compared to what? We mostly hear that pygfx performs much better than other tools.

**Comment by panxinmiao** [comment]
> For lines, we cannot apply this trick, because it needs access to the next and previous vertex. So it'd mean having different code paths and added complexity.

If this approach is taken, it is necessary to pre-generate the data of adjacent vertices for each vertex during the resource loading and preparation phase, as part of the vertex data for that vertex. Note that this only needs to be done once during the entire program.

> 
> What performance loss do you mean here? Loss compared to what? We mostly hear that pygfx performs much better than other tools.

The performance loss mentioned here refers to the comparison with its own faster implementation method. This is just to explain that some computations during rendering can be omitted and be done in advance, during the resource loading and preparation stage, so that they only need to be executed once throughout the entire program runtime.

Although pygfx already has excellent performance, these optimizations can make its performance even better.

**Comment by almarklein** [comment]
> If this approach is taken, it is necessary to pre-generate the data of adjacent vertices for each vertex [...] Note that this only needs to be done once during the entire program.

Data can change, meshes can be morphed, points moved, and lines bend. Any extra work moved out of the shader, now has to be done in Python, which may make dynamic use-cases (where data is changed) much slower.

As it currently is, one can feed the data as-is, which is a huge advantage IMO, in terms of simplicity, predictable performance, and predictable memory consumption.

> Although pygfx already has excellent performance, these optimizations can make its performance even better.

I'm not convinced that they will improve performance. Maybe for some use-cases, but they might degrade performance for other use-cases.

Again, I'm happy to look at performance improvements - once the code has settled more - but only using a set of benchmarks to represent a variety of benchmarks.

**Comment by panxinmiao** [comment]
>> the access speed of StorageBuffer itself is much lower than VertexBuffer

> From what I've read this is not the case for modern hardware, and I was also not able to detect a difference in performance at the time. That said, it could be that in e.g. very large meshes it becomes more noticeable.

I spent some time making some disruptive modifications to pygfx, using VertexBuffer instead of StorageBuffer, to test the performance. 
Contrary to my expectations, the difference was indeed negligible. Although I still find it difficult to understand, the test results are indeed as such, 😓. 
It seems that the performance difference between VertexBuffer and StorageBuffer is insignificant compared to other parts of the rendering process.
Based on this result, I believe that the current solution chosen by pygfx for the convenience of scientific data visualization is indeed very reasonable. I sincerely apologize for my previous comments, which were based on speculation and guesswork.

Furthermore, regarding my previous idea of "moving computations forward as much as possible to reduce the amount of computation in the shaders," I still have reservations, but perhaps it is not important, and is merely some icing on the cake in terms of optimization.

**Comment by almarklein** [comment]
Thanks a lot for taking the time to modify the code and try it out! I feel relieved that you get similar results 😅. 

> [...] which were based on speculation and guesswork.

And on decades of GPU code/tutorials/best-practices 😉. I think its relatively recent that hardware supports storage buffers so well.

**Comment by Korijn** [comment]
We respect your opinion @panxinmiao don't feel bad. You are clearly an experienced graphics programmer. Thank you for dedicating yourself to this project.
