### ISSUE TITLE
Decreasing the number of clipping planes to 0 causes the rendering to fail

### ISSUE THREAD

**Issue by hmaarrfk** [pygfx/pygfx#668]
Version: main
Python: 3.10
OS: Linux

Modifying the example:

```patch
diff --git a/examples/introductory/clipping_planes.py b/examples/introductory/clipping_planes.py
index 936f6b3..bbb624d 100644
--- a/examples/introductory/clipping_planes.py
+++ b/examples/introductory/clipping_planes.py
@@ -9,6 +9,7 @@ Example demonstrating clipping planes on a mesh.
 
 from wgpu.gui.auto import WgpuCanvas, run
 import pygfx as gfx
+from time import perf_counter
 
 
 # Create a canvas and a renderer
@@ -52,12 +53,16 @@ camera.show_object(scene1)
 controller = gfx.OrbitController(camera, register_events=renderer)
 
 
+start_time = perf_counter()
 def animate():
     w, h = canvas.get_logical_size()
     renderer.render(scene1, camera, flush=False, rect=(0, 0, w / 2, h))
     renderer.render(scene2, camera, flush=False, rect=(w / 2, 0, w / 2, h))
     renderer.flush()
 
+    if perf_counter() - start_time > 1:
+        scene1.children[0].material.clipping_planes = []
+
     canvas.request_draw()
 
 

```

```python
Detected skylake derivative running on mesa i915. Clears to srgb textures will use manual shader clears.
Device::create_shader_module error: 
Shader '' parsing error: invalid field accessor `clipping_planes`
    ┌─ wgsl:147:40
    │
147 │                 let plane = u_material.clipping_planes[i];
    │                                        ^^^^^^^^^^^^^^^ invalid accessor


Draw error
Traceback (most recent call last):
  File "/home/mark/git/wgpu-py/wgpu/gui/base.py", line 24, in log_exception
    yield
  File "/home/mark/git/wgpu-py/wgpu/gui/base.py", line 211, in _draw_frame_and_present
    self.draw_frame()
  File "/home/mark/git/pygfx/examples/introductory/clipping_planes.py", line 59, in animate
    renderer.render(scene1, camera, flush=False, rect=(0, 0, w / 2, h))
  File "/home/mark/git/pygfx/pygfx/renderers/wgpu/_renderer.py", line 512, in render
    container_group = get_pipeline_container_group(wobject, environment)
  File "/home/mark/git/pygfx/pygfx/renderers/wgpu/_pipeline.py", line 166, in get_pipeline_container_group
    pipeline_container_group.update(wobject, environment, changed_labels)
  File "/home/mark/git/pygfx/pygfx/renderers/wgpu/_pipeline.py", line 422, in update
    container.update(wobject, environment, changed)
  File "/home/mark/git/pygfx/pygfx/renderers/wgpu/_pipeline.py", line 498, in update
    raise err
  File "/home/mark/git/pygfx/pygfx/renderers/wgpu/_pipeline.py", line 495, in update
    self.update_wgpu_data(wobject, environment, env_hash, changed)
  File "/home/mark/git/pygfx/pygfx/renderers/wgpu/_pipeline.py", line 538, in update_wgpu_data
    self.wgpu_shaders[env_hash] = self._compile_shaders(environment)
  File "/home/mark/git/pygfx/pygfx/renderers/wgpu/_pipeline.py", line 748, in _compile_shaders
    shader_module = get_cached_shader_module(
  File "/home/mark/git/pygfx/pygfx/renderers/wgpu/_pipeline.py", line 80, in get_cached_shader_module
    result = device.create_shader_module(code=wgsl)
  File "/home/mark/git/wgpu-py/wgpu/backends/wgpu_native/_api.py", line 1326, in create_shader_module
    id = libf.wgpuDeviceCreateShaderModule(self._internal, struct)
  File "/home/mark/git/wgpu-py/wgpu/backends/wgpu_native/_helpers.py", line 314, in proxy_func
    raise wgpu_error  # the frame above is more interesting ↑↑
wgpu._classes.GPUValidationError: Validation Error

Caused by:
    In wgpuDeviceCreateShaderModule

Shader '' parsing error: invalid field accessor `clipping_planes`
    ┌─ wgsl:147:40
    │
147 │                 let plane = u_material.clipping_planes[i];
    │                                        ^^^^^^^^^^^^^^^ invalid accessor


    invalid field accessor `clipping_planes`
No texture to present, missing call to get_current_texture()?

```

* Updated code: [clipping_planes.py.txt](https://github.com/pygfx/pygfx/files/14481586/clipping_planes.py.txt)

A workaround is to set the clipping planes to be "very far" when you want to enable them and disable them dynamically.

**Comment by hmaarrfk** [comment]
It seems you can "increase" the number of clipping planes dynamically (at least I was able to do so dynamically in my application from 0 to 4)

**Comment by almarklein** [comment]
I can reproduce this. Decreasing the number of clip planes seems to have unexpected behavior too. The problem is that although the uniform buffer's size is updated, the shader code has the number of planes hard-coded, and needs to be re-compiled for the changes to take effect.
