### ISSUE TITLE
shader error with `int32` and `uint32` `Buffer`

### ISSUE THREAD

**Issue by kushalkolar** [pygfx/pygfx#671]
It seems like `int32` and `uint32` are not supported by `Buffer`. I'm on the latest release of `wgpu-py`, i.e. 0.14.1 and on the current pygfx@main which is this commit https://github.com/pygfx/pygfx/commit/5c1e46d05f34ab140dad0a805d4019b22ef2d6f4 

I'm not sure what's the right solution here, modify the shader code to allow `uint32` and `int32`, or raise an earlier error in `Buffer.__init__()` if these types are passed?

## Example with positions

```python
import numpy as np
from wgpu.gui.auto import WgpuCanvas, run
import pygfx as gfx


canvas = WgpuCanvas()
renderer = gfx.WgpuRenderer(canvas)

scene = gfx.Scene()

xs = np.linspace(0, 20 * np.pi, 500)
ys = np.sin(xs) * 10
zs = np.zeros(xs.size)

# this results in the shader error
positions = np.column_stack([xs, ys, zs]).astype(np.int32)

# this will work
# positions = positions.astype(np.float32)

sizes = np.array([5] * xs.size).astype(np.float32)
colors = np.random.rand(xs.size, 4).astype(np.float32)

geometry = gfx.Geometry(positions=positions, sizes=sizes, colors=colors)

material = gfx.PointsMaterial(color_mode="vertex", vertex_sizes=True)
points = gfx.Points(
    gfx.Geometry(positions=positions, sizes=sizes, colors=colors),
    material=gfx.PointsMaterial(color_mode="vertex", vertex_sizes=True)
)

scene.add(points)


camera = gfx.OrthographicCamera()
camera.show_object(scene)


if __name__ == "__main__":
    canvas.request_draw(lambda: renderer.render(scene, camera))
    run()
```

Results in:

```python
Device::create_shader_module error: 
Shader '' parsing error: automatic conversions cannot convert `vec3<i32>` to `vec3<f32>`
    ┌─ wgsl:140:27
    │
140 │             let raw_pos = load_s_positions(i0);
    │                           ^^^^^^^^^^^^^^^^^^^^ this expression has type vec3<i32>
141 │             let world_pos = u_wobject.world_transform * vec4<f32>(raw_pos, 1.0);
    │                                                         ^^^^^^^^^ a value of type vec3<f32> is required here


Draw error
Traceback (most recent call last):
  File "/home/kushal/venvs/mescore/lib/python3.11/site-packages/wgpu/gui/base.py", line 24, in log_exception
    yield
  File "/home/kushal/venvs/mescore/lib/python3.11/site-packages/wgpu/gui/base.py", line 211, in _draw_frame_and_present
    self.draw_frame()
  File "/home/kushal/repos/pygfx/examples/introductory/points_basic.py", line 40, in <lambda>
    canvas.request_draw(lambda: renderer.render(scene, camera))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/_renderer.py", line 512, in render
    container_group = get_pipeline_container_group(wobject, environment)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/_pipeline.py", line 166, in get_pipeline_container_group
    pipeline_container_group.update(wobject, environment, changed_labels)
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/_pipeline.py", line 422, in update
    container.update(wobject, environment, changed)
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/_pipeline.py", line 498, in update
    raise err
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/_pipeline.py", line 495, in update
    self.update_wgpu_data(wobject, environment, env_hash, changed)
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/_pipeline.py", line 538, in update_wgpu_data
    self.wgpu_shaders[env_hash] = self._compile_shaders(environment)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/_pipeline.py", line 748, in _compile_shaders
    shader_module = get_cached_shader_module(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/_pipeline.py", line 80, in get_cached_shader_module
    result = device.create_shader_module(code=wgsl)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/venvs/mescore/lib/python3.11/site-packages/wgpu/backends/wgpu_native/_api.py", line 1326, in create_shader_module
    id = libf.wgpuDeviceCreateShaderModule(self._internal, struct)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/venvs/mescore/lib/python3.11/site-packages/wgpu/backends/wgpu_native/_helpers.py", line 314, in proxy_func
    raise wgpu_error  # the frame above is more interesting ↑↑
    ^^^^^^^^^^^^^^^^
wgpu._classes.GPUValidationError: Validation Error

Caused by:
    In wgpuDeviceCreateShaderModule

Shader '' parsing error: automatic conversions cannot convert `vec3<i32>` to `vec3<f32>`
    ┌─ wgsl:140:27
    │
140 │             let raw_pos = load_s_positions(i0);
    │                           ^^^^^^^^^^^^^^^^^^^^ this expression has type vec3<i32>
141 │             let world_pos = u_wobject.world_transform * vec4<f32>(raw_pos, 1.0);
    │                                                         ^^^^^^^^^ a value of type vec3<f32> is required here


    automatic conversions cannot convert `vec3<i32>` to `vec3<f32>`
No texture to present, missing call to get_current_texture()?

Process finished with exit code 0
```

If we convert the int32 to float32 we then get what we expect:

![image](https://github.com/pygfx/pygfx/assets/9403332/81b45213-37da-4599-ab31-009606b4ecfc)

## This is also true forsizes, example if we change the sizes on line 21:

```python
sizes = np.array([5] * xs.size).astype(np.float32).astype(np.int32)
```

I get:

```python
Left: CallResult([2]) of type Scalar(Scalar { kind: Sint, width: 4 })
Right: Literal(F32(1.0)) of type Scalar(Scalar { kind: Float, width: 4 })
Device::create_shader_module error: 
Shader validation error: 
    ┌─ :156:54
    │
156 │             let delta_logical = deltas[sub_index] * (size + aa_margin);
    │                                                      ^^^^^^^^^^^^^^^^ naga::Expression [47]


Draw error
Traceback (most recent call last):
  File "/home/kushal/venvs/mescore/lib/python3.11/site-packages/wgpu/gui/base.py", line 24, in log_exception
    yield
  File "/home/kushal/venvs/mescore/lib/python3.11/site-packages/wgpu/gui/base.py", line 211, in _draw_frame_and_present
    self.draw_frame()
  File "/home/kushal/repos/pygfx/examples/introductory/points_basic.py", line 40, in <lambda>
    canvas.request_draw(lambda: renderer.render(scene, camera))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/_renderer.py", line 512, in render
    container_group = get_pipeline_container_group(wobject, environment)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/_pipeline.py", line 166, in get_pipeline_container_group
    pipeline_container_group.update(wobject, environment, changed_labels)
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/_pipeline.py", line 422, in update
    container.update(wobject, environment, changed)
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/_pipeline.py", line 498, in update
    raise err
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/_pipeline.py", line 495, in update
    self.update_wgpu_data(wobject, environment, env_hash, changed)
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/_pipeline.py", line 538, in update_wgpu_data
    self.wgpu_shaders[env_hash] = self._compile_shaders(environment)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/_pipeline.py", line 748, in _compile_shaders
    shader_module = get_cached_shader_module(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/_pipeline.py", line 80, in get_cached_shader_module
    result = device.create_shader_module(code=wgsl)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/venvs/mescore/lib/python3.11/site-packages/wgpu/backends/wgpu_native/_api.py", line 1326, in create_shader_module
    id = libf.wgpuDeviceCreateShaderModule(self._internal, struct)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/venvs/mescore/lib/python3.11/site-packages/wgpu/backends/wgpu_native/_helpers.py", line 314, in proxy_func
    raise wgpu_error  # the frame above is more interesting ↑↑
    ^^^^^^^^^^^^^^^^
wgpu._classes.GPUValidationError: Validation Error

Caused by:
    In wgpuDeviceCreateShaderModule

Shader validation error:
    ┌─ :156:54
    │
156 │             let delta_logical = deltas[sub_index] * (size + aa_margin);
    │                                                      ^^^^^^^^^^^^^^^^ naga::Expression [47]


    Entry point vs_main at Vertex is invalid
    Expression [47] is invalid
    Operation Add can't work with [43] and [44]
No texture to present, missing call to get_current_texture()?
```

## And colors as well

If I change line 22 to:

```python
colors = np.random.rand(xs.size, 4).astype(np.float32).astype(np.int32)
```

Results in a blank canvas with but no traceback or any other message.

**Comment by almarklein** [comment]
Could you try modifying the shader to:
```wgsl
let raw_pos = vec3<f32>(load_s_positions(i0));
```

From what I can tell, the rest of the logic should handle the type correctly. It seems to fail when combined into a vector with `1.0`.
