### ISSUE TITLE
Error changing material color when adding or removing alpha channel

### ISSUE THREAD

**Issue by schlegelp** [pygfx/pygfx#682]
Hi! I ran into an error trying to change mesh colors on-the-fly, i.e. on a running ,non-blocking window.

```python
>>> # Generate mesh
>>> cube = gfx.Mesh(gfx.box_geometry(200, 200, 200), gfx.MeshPhongMaterial(color="#336699"))
>>> # Add to already being rendered scene
>>> scene.add(cube)
>>> # Changing color like this works like a charm 
>>> cube.material.color = gfx.Color("r")

>>> # Now the same thing but we use a (r, g, b, a) color
>>> cube2 = gfx.Mesh(gfx.box_geometry(200, 200, 200), gfx.MeshPhongMaterial(color=(0, 0, 1, .5)))
>>> scene.add(cube2)
>>> cube2.material.color = gfx.Color("r")

Draw error: 0 (57)
No texture to present, missing call to get_current_texture()?
```

After a bit of experimentation it seems that if the material is initialized with an alpha channel, we break things by trying to assign a color without alpha channel. The other way around causes the same issue. I don't know whether that's expected and/or fixable but perhaps in the first instance the `.color` setter method could prohibit adding/removing the alpha channel?

**Comment by Korijn** [comment]
Can you share a minimal reproduction script? The error seems to indicate a different cause, so I'd be interested to see how the rest of your code looks.

**Comment by schlegelp** [comment]
Sure!

In`ipython`:
```python
>>> %gui qt6

>>> import pygfx as gfx
>>> from wgpu.gui.auto import WgpuCanvas

>>> canvas = WgpuCanvas()
>>> renderer = gfx.renderers.WgpuRenderer(canvas)

>>> scene = gfx.Scene()
>>> scene.add(gfx.AmbientLight())
>>> scene.add(gfx.DirectionalLight())

>>> camera = gfx.OrthographicCamera()
>>> controller = gfx.TrackballController(camera, register_events=renderer)

>>> def animate():
>>>     renderer.render(scene, camera)
>>>     canvas.request_draw()

>>> # Add a cube
>>> cube = gfx.Mesh(gfx.box_geometry(200, 200, 200), gfx.MeshPhongMaterial(color="#336699"))
>>> scene.add(cube)
>>> camera.show_object(scene)

>>> # After this point the scene is actively rendered
>>> canvas.request_draw(animate)

>>> # Changing color like this works:
>>> cube.material.color = gfx.Color("r")

>>> # Changing color like this breaks
>>> cube.material.color = gfx.Color((1, 0, 0, .1))
Draw error
Traceback (most recent call last):
  File "[...]/python3.11/site-packages/wgpu/gui/_gui_utils.py", line 27, in log_exception
    yield
  File "[...]/python3.11/site-packages/wgpu/gui/base.py", line 135, in _draw_frame_and_present
    self.draw_frame()
  File "<ipython-input-2-abc333fa58e0>", line 15, in animate
    renderer.render(scene, camera)
  File "[...]python3.11/site-packages/pygfx/renderers/wgpu/_renderer.py", line 532, in render
    command_buffers += self._render_recording(
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]python3.11/site-packages/pygfx/renderers/wgpu/_renderer.py", line 658, in _render_recording
    render_pipeline_container.draw(
  File "[...]/3.11.8/lib/python3.11/site-packages/pygfx/renderers/wgpu/_pipeline.py", line 814, in draw
    pipeline = self.wgpu_pipelines[env_hash][pass_index]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 1
No texture to present, missing call to get_current_texture()?
```

Previously,  had the code for the setup in a module which seems to swallow the detailed traceback and just shows the "No texture present, ..." message. Hope this is more helpful!

PS: this is with `pygfx=0.1.18` and `wgpu=0.15.0`.

**Comment by Korijn** [comment]
Thanks, we'll look into it soon.

**Comment by almarklein** [comment]
The `No texture to present, missing call to get_current_texture()?` is actually a secondary error/warning message unrelated to the `KeyError` (the first error messes up the flow so the swap-buffer mechanics warns about the situation)

**Comment by almarklein** [comment]
I think what's going on is that first the meshes are opaque, so no transparency pass is needed. Then the color is changed, making the mesh semi-transparent, so the renderer now needs a pipeline object for the transparency pass, but it does not exist yet.

**Comment by schlegelp** [comment]
Thanks for looking into this!

In case that's helpful in homing in on the underlying issue: the same happens when starting with a transparent mesh and changing the color to opaque:

```python
>>> # Using setup from above snippet

>>> # Initialize cube with transparent material
>>> cube = gfx.Mesh(gfx.box_geometry(200, 200, 200), gfx.MeshPhongMaterial(color=(1, 0, 0, .1)))

>>> scene.add(cube)
>>> camera.show_object(scene)

>>> # After this point the scene is actively rendered
>>> canvas.request_draw(animate)

>>> # Change color to opaque
>>> cube.material.color = gfx.Color("b")
Draw error
Traceback (most recent call last):
  File "/Users/philipps/.pyenv/versions/3.11.8/lib/python3.11/site-packages/wgpu/gui/_gui_utils.py", line 27, in log_exception
    yield
  File "/Users/philipps/.pyenv/versions/3.11.8/lib/python3.11/site-packages/wgpu/gui/base.py", line 135, in _draw_frame_and_present
    self.draw_frame()
  File "<ipython-input-2-0f20c2227c86>", line 15, in animate
    renderer.render(scene, camera)
  File "[...]/python3.11/site-packages/pygfx/renderers/wgpu/_renderer.py", line 532, in render
    command_buffers += self._render_recording(
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/python3.11/site-packages/pygfx/renderers/wgpu/_renderer.py", line 658, in _render_recording
    render_pipeline_container.draw(
  File "[...]/python3.11/site-packages/pygfx/renderers/wgpu/_pipeline.py", line 814, in draw
    pipeline = self.wgpu_pipelines[env_hash][pass_index]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 0
No texture to present, missing call to get_current_texture()?
Draw error: 0 (2)
```

**Comment by almarklein** [comment]
A nice!  Yes, that's the same problem, except now its the pipeline object for the opaque pass that's missing :)

**Comment by almarklein** [comment]
The cause is pretty clear. The solution ... working on it 😅. Some similar case happens when using vertex colors and changing these from rgb to rgba. Produces a different error though.
