### ISSUE TITLE
WxWgpuWindow object has no attribute 'add_event_handler'

### ISSUE THREAD

**Issue by cansik** [pygfx/pygfx#694]
At least on MacOS, it seems that the `WxWgpuWindow` integration seems not to work. The [example found](https://pygfx.readthedocs.io/en/stable/_gallery/other/cube_wx.html) here can not be run because of the following issue:

```python
Traceback (most recent call last):
  File "/pyfx_image_viewer.py", line 11, in <module>
    canvas = WgpuCanvas()
  File "/venv/lib/python3.9/site-packages/wgpu/gui/wx.py", line 146, in __init__
    self._subwidget.add_event_handler(weakbind(self.handle_event), "*")
AttributeError: 'WxWgpuWindow' object has no attribute 'add_event_handler'
```

Versions:
- pygfx `0.1.18`
- wgpu `0.15.0`
- wxpython `4.2.1`

**Comment by Korijn** [comment]
Are you experienced with Wx? We're looking for maintainers for the wx backend.

**Comment by cansik** [comment]
It seems that the issue is related to the [wgpu-py](https://github.com/pygfx/wgpu-py) package. I am not even sure why this has been added (https://github.com/pygfx/wgpu-py/commit/7dcd6aef343f0c811d41bceec3c892b311ac7507), it seems to it has been added to wx and qt as well. Do you have more information about that line?

If this line is removed, there is another issue inside the [timer start](https://github.com/pygfx/wgpu-py/blob/main/wgpu/gui/wx.py#L124). At the moment `0` can be passed as wait time, even that is not an allowed value. Adding a `max(1, ...)` and converting to `int` solves this issue:

```python
  def _request_draw(self):
      # Despite the FPS limiting the delayed call to refresh solves
      # that drawing only happens when the mouse is down, see #209.
      if not self._request_draw_timer.IsRunning():
          self._request_draw_timer.Start(
              max(1, int(self._get_draw_wait_time() * 1000)), wx.TIMER_ONE_SHOT
          )
```

@Korijn I wouldn't call myself experienced, however, I would like to have pygfx support in wx.

**Comment by Korijn** [comment]
Indeed the gui backends are implemented in wgpu-py. You'd have to fix this there. I'll transfer the issue for you.
