### ISSUE TITLE
Unable to run with latest wgpu@main

### ISSUE THREAD

**Issue by kushalkolar** [pygfx/pygfx#815]
Hi, sorry if you're already aware of this or have it planned for later. Seems like something changed in the current wgpu@main that makes it incompatible with the current pygfx@main. For example if I try to run the triangle example I get the following. WGPU examples run fine.

```python
Draw error
Traceback (most recent call last):
  File "/home/kushal/repos/wgpu-py/wgpu/gui/_gui_utils.py", line 77, in log_exception
    yield
  File "/home/kushal/repos/wgpu-py/wgpu/gui/base.py", line 135, in _draw_frame_and_present
    self.draw_frame()
  File "/home/kushal/repos/pygfx/examples/introductory/hello_triangle.py", line 30, in <lambda>
    canvas.request_draw(lambda: renderer.render(triangle, camera))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/engine/renderer.py", line 511, in render
    container_group = get_pipeline_container_group(wobject, environment)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/engine/pipeline.py", line 159, in get_pipeline_container_group
    pipeline_container_group.update(wobject, environment, changed_labels)
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/engine/pipeline.py", line 239, in update
    container.update(wobject, environment, env_hash, changed)
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/engine/pipeline.py", line 324, in update
    raise err
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/engine/pipeline.py", line 321, in update
    self.update_wgpu_data(environment, env_hash, changed)
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/engine/pipeline.py", line 399, in update_wgpu_data
    env_pipelines[pass_index] = self._compose_pipeline(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/engine/pipeline.py", line 620, in _compose_pipeline
    return get_cached_render_pipeline(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/pygfx/pygfx/renderers/wgpu/engine/pipeline.py", line 109, in get_cached_render_pipeline
    result = device.create_render_pipeline(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kushal/repos/wgpu-py/wgpu/backends/wgpu_native/_api.py", line 1570, in create_render_pipeline
    c_alpha_blend, c_color_blend = [
                                   ^
  File "/home/kushal/repos/wgpu-py/wgpu/backends/wgpu_native/_api.py", line 1574, in <listcomp>
    srcFactor=blend.get("src_factor", "one"),
              ^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'get'
Draw error: 'tuple' object has no attribute 'get' (2)
No work has been submitted for this frame
```

**Comment by kushalkolar** [comment]
OK it's from here: https://github.com/pygfx/wgpu-py/pull/533/files#diff-b6d509f99c0fdb1eb6151ae6f14bd78eb3981614388816189b59d3a1d2e2fc86R1570-R1582 

A bit confused how this is creating issues in pygfx only though.

**Comment by almarklein** [comment]
Thanks for reporting! Woops, looks like these changes affect pygfx. I had not checked this yet myself apparently. Sorry for the inconvenience! I'll have a look right away.
