### ISSUE TITLE
Validation Error while creating Texture Geometry -> Grid

### ISSUE THREAD

**Issue by sharon92** [pygfx/pygfx#863]
While creating a surface plot for an image with dimensions `(3,3344,5822)`, a `GPUValidationError` is thrown.

The limits seems to be set at 2048, could this be changed dynamically?

Code Snippet:
```
        geometry = gfx.Geometry(grid=arr.astype(np.float32))
        material = gfx.VolumeIsoMaterial(clim=(0, 2000), threshold=1000)

        vol1 = gfx.Volume(geometry, material)
        self._scene.add(vol1)
```
Traceback:
```
Device::create_texture error: Dimension X value 5822 exceeds the limit of 2048
Draw error
Traceback (most recent call last):
  File "C:\Py312\Lib\site-packages\wgpu\gui\_gui_utils.py", line 77, in log_exception
    yield
  File "C:\Py312\Lib\site-packages\wgpu\gui\base.py", line 135, in _draw_frame_and_present
    self.draw_frame()
  File "c:\projekte\tutorial\stars_extract.py", line 69, in animate
    self._renderer.render(self._scene, self._camera)
  File "C:\Py312\Lib\site-packages\pygfx\renderers\wgpu\engine\renderer.py", line 511, in render
    container_group = get_pipeline_container_group(wobject, environment)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py312\Lib\site-packages\pygfx\renderers\wgpu\engine\pipeline.py", line 159, in get_pipeline_container_group
    pipeline_container_group.update(wobject, environment, changed_labels)
  File "C:\Py312\Lib\site-packages\pygfx\renderers\wgpu\engine\pipeline.py", line 239, in update
    container.update(wobject, environment, env_hash, changed)
  File "C:\Py312\Lib\site-packages\pygfx\renderers\wgpu\engine\pipeline.py", line 314, in update
    raise err
  File "C:\Py312\Lib\site-packages\pygfx\renderers\wgpu\engine\pipeline.py", line 311, in update
    self.update_shader_data(wobject, changed)
  File "C:\Py312\Lib\site-packages\pygfx\renderers\wgpu\engine\pipeline.py", line 347, in update_shader_data
    self.update_bind_groups()
  File "C:\Py312\Lib\site-packages\pygfx\renderers\wgpu\engine\pipeline.py", line 442, in update_bind_groups
    binding_des, binding_layout_des = binding.get_bind_group_descriptors(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py312\Lib\site-packages\pygfx\renderers\wgpu\engine\binding.py", line 134, in get_bind_group_descriptors
    "resource": ensure_wgpu_object(resource),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py312\Lib\site-packages\pygfx\renderers\wgpu\engine\update.py", line 153, in ensure_wgpu_object
    wgpu_texture = ensure_wgpu_object(resource.texture)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py312\Lib\site-packages\pygfx\renderers\wgpu\engine\update.py", line 141, in ensure_wgpu_object
    resource._wgpu_object = device.create_texture(
                            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py312\Lib\site-packages\wgpu\backends\wgpu_native\_api.py", line 1149, in create_texture
    id = libf.wgpuDeviceCreateTexture(self._internal, struct)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Py312\Lib\site-packages\wgpu\backends\wgpu_native\_helpers.py", line 329, in proxy_func
    raise wgpu_error  # the frame above is more interesting ↑↑
    ^^^^^^^^^^^^^^^^
wgpu._classes.GPUValidationError: Validation Error

Caused by:
  In wgpuDeviceCreateTexture
    Dimension X value 5822 exceeds the limit of 2048
```

**Comment by almarklein** [comment]
Wgpu applies some limits (of which the max texture sizes are probably the most impactful) https://gpuweb.github.io/gpuweb/#limit-default

In pygfx you can set these limits (before creating the first renderer) using e.g.
```py
gfx.renderers.wgpu.set_wgpu_limits(maxTextureDimension3D=3000)
```

You cannot set limits higher than those of the adapter. From what I've seen, these adapter limits are usually not higher than the default limits. I may have to dive into this deeper, because it seems like a reasonable use-case to ask for larger textures?

----

Note that a 3D texture has a much lower limit than a 2D texture. What's the purpose of the 3d dimension in your code?

**Comment by sharon92** [comment]
> What's the purpose of the 3d dimension in your code?

I am trying to create a surface plot for an astro image that I took. The third dimension is the magnitude (normalized brightness  [0-1]) of the stars, later I want to switch the third dimension to the distance from earth in light years. Later, I want to save this as a 3D Object.

The X and Y dimensions are just the size of the camera sensor in pixels, so typically 4k*6.5k pixels

**Comment by almarklein** [comment]
You can try creating a Texture that represents a stack of 2D images, so that the 2D texture limit applies. 

In wgpu, this works:
```py
>>> d.create_texture(size=(3000, 3000, 3), format=wgpu.TextureFormat.r16float, dimension="2d", usage=wgpu.TextureUsage.RENDER_ATTACHMENT)
<wgpu.backends.wgpu_native.GPUTexture object '' at 0x108cf9010>
```


I have not tried this in pygfx, but I think using `Texture(..., dim=2`) should do the trick.
