### ISSUE TITLE
Setting colormap to None after material has been rendered results in error

### ISSUE THREAD

**Issue by claydugo** [pygfx/pygfx#881]
<details>
  <summary>Reproducer</summary>

```python
import imageio.v3 as iio
import pygfx as gfx
from imgui_bundle import imgui
from wgpu.gui.auto import WgpuCanvas, run
from wgpu.utils.imgui import ImguiRenderer

scene = gfx.Scene()
canvas = WgpuCanvas(size=(800, 600), title="Set cmap to None")
renderer = gfx.renderers.WgpuRenderer(canvas)
camera = gfx.PerspectiveCamera(0)
camera.local.scale_y = -1
controller = gfx.PanZoomController(camera, register_events=renderer)

image = iio.imread("imageio:astronaut.png")[:, :, 0]

texture = gfx.Texture(image, dim=2)
geometry = gfx.Geometry(grid=texture)
material = gfx.ImageBasicMaterial(clim=(0, 255), pick_write=True)
gfx_image = gfx.Image(geometry, material)
gfx_image.material.map = gfx.cm.viridis

scene.add(gfx_image)
camera.show_object(scene, view_dir=(0, 0, 1))

gui_renderer = ImguiRenderer(renderer.device, canvas)

def draw_imgui():
    imgui.new_frame()
    imgui.begin("Controls")

    if imgui.button("Set map to None"):
        gfx_image.material.map = None

    if imgui.button("New material no cmap"):
        new_material = gfx.ImageBasicMaterial(clim=(0, 255))
        gfx_image.material = new_material

    imgui.end()
    imgui.render()
    return imgui.get_draw_data()

gui_renderer.set_gui(draw_imgui)

def animate():
    renderer.render(scene, camera)
    gui_renderer.render()
    canvas.request_draw()

if __name__ == "__main__":
    renderer.request_draw(animate)
    run()

```

</details>

<details>
  <summary>Traceback</summary>

```

Traceback (most recent call last):
  File "/home/clay/miniforge3/envs/mcam_dev/lib/python3.10/site-packages/wgpu/gui/_gui_utils.py", line 77, in log_exception
    yield
  File "/home/clay/miniforge3/envs/mcam_dev/lib/python3.10/site-packages/wgpu/gui/base.py", line 135, in _draw_frame_and_present
    self.draw_frame()
  File "/tmp/editing-mode.lV2/minpls.py", line 51, in animate
    renderer.render(scene, camera)
  File "/home/clay/git/forks/pygfx/pygfx/renderers/wgpu/engine/renderer.py", line 511, in render
    container_group = get_pipeline_container_group(wobject, environment)
  File "/home/clay/git/forks/pygfx/pygfx/renderers/wgpu/engine/pipeline.py", line 159, in get_pipeline_container_group
    pipeline_container_group.update(wobject, environment, changed_labels)
  File "/home/clay/git/forks/pygfx/pygfx/renderers/wgpu/engine/pipeline.py", line 239, in update
    container.update(wobject, environment, env_hash, changed)
  File "/home/clay/git/forks/pygfx/pygfx/renderers/wgpu/engine/pipeline.py", line 324, in update
    raise err
  File "/home/clay/git/forks/pygfx/pygfx/renderers/wgpu/engine/pipeline.py", line 321, in update
    self.update_wgpu_data(environment, env_hash, changed)
  File "/home/clay/git/forks/pygfx/pygfx/renderers/wgpu/engine/pipeline.py", line 400, in update_wgpu_data
    env_pipelines[pass_index] = self._compose_pipeline(
  File "/home/clay/git/forks/pygfx/pygfx/renderers/wgpu/engine/pipeline.py", line 621, in _compose_pipeline
    return get_cached_render_pipeline(
  File "/home/clay/git/forks/pygfx/pygfx/renderers/wgpu/engine/pipeline.py", line 109, in get_cached_render_pipeline
    result = device.create_render_pipeline(
  File "/home/clay/miniforge3/envs/mcam_dev/lib/python3.10/site-packages/wgpu/backends/wgpu_native/_api.py", line 1765, in create_render_pipeline
    id = libf.wgpuDeviceCreateRenderPipeline(self._internal, struct)
  File "/home/clay/miniforge3/envs/mcam_dev/lib/python3.10/site-packages/wgpu/backends/wgpu_native/_helpers.py", line 329, in proxy_func
    raise wgpu_error  # the frame above is more interesting ↑↑
wgpu._classes.GPUValidationError: Validation Error

Caused by:
  In wgpuDeviceCreateRenderPipeline
    Error matching ShaderStages(FRAGMENT) shader requirements against the pipeline
      Shader global ResourceBinding { group: 0, binding: 5 } is not available in the pipeline layout
        Binding is missing from the pipeline layout

```

</details>

The way I am reading the [setter](https://github.com/pygfx/pygfx/blob/e9039f31f2152542fe5a2943453131590f950008/pygfx/materials/_image.py#L52-L55) I would think this operation is allowed. 

If I am doing something wrong what would be the correct way to remove the colormap from a material?

**Comment by hmaarrfk** [comment]
I definitely hit this months ago too.

Interestingly, adding these two lines:
```
    if imgui.button("cividis cmap"):
        gfx_image.material.map = gfx.cm.cividis
    if imgui.button("viridis cmap"):
        gfx_image.material.map = gfx.cm.viridis
```
makes you able to change colormaps.

(actually this bug is why we always have a colormap within our application clay).

I feel like the shader code isn't being invalidated somewhere.... because the "5th binding" is the colormap that is created in https://github.com/pygfx/pygfx/blob/main/pygfx/renderers/wgpu/shaders/imageshader.py#L69 that is only conditionally defined.

Some other related though not exactly the same bugs are https://github.com/pygfx/pygfx/issues/686
