### ISSUE TITLE
Adding AxesHelper to scene causes RuntimeError: Waiting for buffer.map timed out

### ISSUE THREAD

**Issue by kevinyamauchi** [pygfx/pygfx#893]
Hello! I get a RuntimeError when I have an AxesHelperin the scene scene and move the camera through the GUI (see traceback below). I can reproduce the issue by just adding the line `scene.add(gfx.AxesHelper(20))` to the `world_bounding_box.py` example (see the "reproducer script". I am on an Intel Mac. I haven't tested on any other operating systems.

Has anybody else come across this issue? Am I using the AxesHelper correctly?

Thanks!

<details>
  <summary>Reproducer script</summary>

I just added the line: `scene.add(gfx.AxesHelper(20))` to the `world_bounding_box.py` example
  
```python
"""
Bounding Box Coordinates
========================

Render two volumes using different world transforms.
Prints the world bounding box of the scene which used
to trigger an Exception.
"""

# sphinx_gallery_pygfx_docs = 'screenshot'
# sphinx_gallery_pygfx_test = 'run'

import imageio.v3 as iio
import numpy as np
from wgpu.gui.auto import WgpuCanvas, run
import pygfx as gfx


canvas = WgpuCanvas()
renderer = gfx.renderers.WgpuRenderer(canvas)
scene = gfx.Scene()

voldata = iio.imread("imageio:stent.npz").astype(np.float32)

geometry = gfx.Geometry(grid=voldata)
geometry_with_texture = gfx.Geometry(grid=gfx.Texture(data=voldata, dim=3))
material = gfx.VolumeRayMaterial(clim=(0, 2000))

vol1 = gfx.Volume(geometry, material)

material_2 = gfx.VolumeRayMaterial(clim=(0, 2000), map=gfx.cm.cividis)
vol2 = gfx.Volume(geometry_with_texture, material_2)
scene.add(vol1, vol2)

vol2.local.x = 150

camera = gfx.PerspectiveCamera(70, 16 / 9)
camera.show_object(scene, view_dir=(-1, -1, -1), up=(0, 0, 1))
controller = gfx.OrbitController(camera, register_events=renderer)

print("World bounding box:\n", scene.get_world_bounding_box())

# add an AxesHelper
scene.add(gfx.AxesHelper(20))


def animate():
    renderer.render(scene, camera)
    canvas.request_draw()


if __name__ == "__main__":
    canvas.request_draw(animate)
    run()

```
</details>

<details>
  <summary>Traceback</summary>

```python

❯ python world_bounding_box.py
World bounding box:
 [[ -0.5  -0.5  -0.5]
 [277.5 127.5 255.5]]
Error during handling pointer_move event
Traceback (most recent call last):
  File "/Users/kyamauch/miniconda3/envs/pygfx/lib/python3.10/site-packages/wgpu/gui/_gui_utils.py", line 76, in log_exception
    yield
  File "/Users/kyamauch/miniconda3/envs/pygfx/lib/python3.10/site-packages/wgpu/gui/base.py", line 322, in handle_event
    callback(event)
  File "/Users/kyamauch/Documents/pygfx/pygfx/renderers/wgpu/engine/renderer.py", line 813, in convert_event
    info = self.get_pick_info((event["x"], event["y"]))
  File "/Users/kyamauch/Documents/pygfx/pygfx/renderers/wgpu/engine/renderer.py", line 713, in get_pick_info
    self._pixel_info_buffer.map_sync("read")
  File "/Users/kyamauch/miniconda3/envs/pygfx/lib/python3.10/site-packages/wgpu/backends/wgpu_native/_api.py", line 2080, in map_sync
    return awaitable.sync_wait()
  File "/Users/kyamauch/miniconda3/envs/pygfx/lib/python3.10/site-packages/wgpu/backends/wgpu_native/_helpers.py", line 268, in sync_wait
    return self.finish()
  File "/Users/kyamauch/miniconda3/envs/pygfx/lib/python3.10/site-packages/wgpu/backends/wgpu_native/_helpers.py", line 260, in finish
    raise RuntimeError(f"Waiting for {self.title} timed out.")
RuntimeError: Waiting for buffer.map timed out.
thread '<unnamed>' panicked at src/lib.rs:582:5:
Error in wgpuQueueSubmit: Validation Error

Caused by:
  Buffer with '' label is still mapped

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:        0x11d5ef273 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::haf41a54e7ed5fe07
   1:        0x11d60bddb - core::fmt::write::h526161fad96c5ad5
   2:        0x11d5ed69e - std::io::Write::write_fmt::h4de0398536c8b0e4
   3:        0x11d5f02ea - std::panicking::default_hook::{{closure}}::hffeef89117b5d267
   4:        0x11d5eff9a - std::panicking::default_hook::h2f20b53f3264c5d5
   5:        0x11d5f0fcf - std::panicking::rust_panic_with_hook::h7919e8c602131afa
   6:        0x11d5f0822 - std::panicking::begin_panic_handler::{{closure}}::h7bd628128f542977
   7:        0x11d5ef749 - std::sys::backtrace::__rust_end_short_backtrace::ha2fdb908654ed930
   8:        0x11d5f046c - _rust_begin_unwind
   9:        0x11d63730c - core::panicking::panic_nounwind_fmt::h12cc2ce627e784e8
  10:        0x11d6373ba - core::panicking::panic_nounwind::h770250030017ec94
  11:        0x11d637495 - core::panicking::panic_cannot_unwind::h37f7072994988adf
  12:        0x11d298806 - _wgpuQueueSubmit
  13:     0x7ff826607892 - <unknown>
  14:     0x7ff82660720e - <unknown>
  15:        0x107daad05 - _cdata_call
  16:        0x1069f1823 - __PyEval_EvalFrameDefault
  17:        0x1068cf3e6 - __PyFunction_Vectorcall
  18:        0x1069f1b84 - __PyEval_EvalFrameDefault
  19:        0x1068cf3e6 - __PyFunction_Vectorcall
  20:        0x1069ee2dd - __PyEval_EvalFrameDefault
  21:        0x1068cf3e6 - __PyFunction_Vectorcall
  22:        0x1069ee2dd - __PyEval_EvalFrameDefault
  23:        0x1068cf3e6 - __PyFunction_Vectorcall
  24:        0x1068d3eae - _method_vectorcall
  25:        0x106a165fb - _call_function
  26:        0x1069e79f5 - __PyEval_EvalFrameDefault
  27:        0x1068cf3e6 - __PyFunction_Vectorcall
  28:        0x1069f02e0 - __PyEval_EvalFrameDefault
  29:        0x1068cf3e6 - __PyFunction_Vectorcall
  30:        0x106a165fb - _call_function
  31:        0x1069e79f5 - __PyEval_EvalFrameDefault
  32:        0x1068cf3e6 - __PyFunction_Vectorcall
  33:        0x1068d3eae - _method_vectorcall
  34:        0x1069f1b84 - __PyEval_EvalFrameDefault
  35:        0x1068cf3e6 - __PyFunction_Vectorcall
  36:        0x1068d3eae - _method_vectorcall
  37:        0x1069f1b84 - __PyEval_EvalFrameDefault
  38:        0x1068cf3e6 - __PyFunction_Vectorcall
  39:        0x1068d3eae - _method_vectorcall
  40:        0x1069f1b84 - __PyEval_EvalFrameDefault
  41:        0x1068cf3e6 - __PyFunction_Vectorcall
  42:        0x1068d3eae - _method_vectorcall
  43:        0x1069f1b84 - __PyEval_EvalFrameDefault
  44:        0x1068cf3e6 - __PyFunction_Vectorcall
  45:        0x1068d3f7b - _method_vectorcall
  46:        0x1181cb818 - __ZN14QWidgetWrapper15mousePressEventEP11QMouseEvent
  47:        0x11a514d75 - __ZN7QWidget5eventEP6QEvent
  48:        0x11a4c59e7 - __ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent
  49:        0x11a4c7cdb - __ZN12QApplication6notifyEP7QObjectP6QEvent
  50:        0x10b3e223a - __ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent
  51:        0x11a4c5fa5 - __ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0_Ebb
  52:        0x11a52bbb4 - __ZNK21QWidgetRepaintManager3rhiEv
  53:        0x11a52a7c9 - __ZNK21QWidgetRepaintManager3rhiEv
  54:        0x11a4c59e7 - __ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent
  55:        0x11a4c680c - __ZN12QApplication6notifyEP7QObjectP6QEvent
  56:        0x10b3e223a - __ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent
  57:        0x119179380 - __ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE
  58:        0x1191d2aac - __ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE
  59:        0x107c73b5d - _qt_plugin_instance
  60:     0x7ff8152cf2c7 - <unknown>
  61:     0x7ff8152cf269 - <unknown>
  62:     0x7ff8152cf034 - <unknown>
  63:     0x7ff8152cdcb1 - <unknown>
  64:     0x7ff8152cd352 - <unknown>
  65:     0x7ff81fb6f9d9 - <unknown>
  66:     0x7ff81fb6f616 - <unknown>
  67:     0x7ff81fb6f531 - <unknown>
  68:     0x7ff8188dd885 - <unknown>
  69:     0x7ff8191d1348 - <unknown>
  70:     0x7ff8188cedfa - <unknown>
  71:        0x107c72577 - _qt_plugin_instance
  72:        0x10b3eba46 - __ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE
  73:        0x10b3e2827 - __ZN16QCoreApplication4execEv
  74:        0x1186c7428 - __ZL25Sbk_QApplicationFunc_execP7_object
  75:        0x10692d715 - _cfunction_vectorcall_NOARGS
  76:        0x1069f1b84 - __PyEval_EvalFrameDefault
  77:        0x1068cf3e6 - __PyFunction_Vectorcall
  78:        0x106a165fb - _call_function
  79:        0x1069e79f5 - __PyEval_EvalFrameDefault
  80:        0x1069e3b01 - __PyEval_Vector
  81:        0x106a6c370 - _run_mod
  82:        0x106a6c135 - _pyrun_file
  83:        0x106a6bc86 - __PyRun_SimpleFileObject
  84:        0x106a6b5af - __PyRun_AnyFileObject
  85:        0x106a908d8 - _pymain_run_file_obj
  86:        0x106a90265 - _pymain_run_file
  87:        0x106a8fa98 - _pymain_run_python
  88:        0x106a8f8d5 - _Py_RunMain
  89:        0x10686a8c8 - _main
  90:     0x7ff814e6b3a6 - <unknown>
thread caused non-unwinding panic. aborting.
[1]    8284 abort      python world_bounding_box.py
```

<\details>

**Comment by almarklein** [comment]
thanks for the report and the script to reproduce the error!

When I run the script (MacOS M1) I don't get the error. What version of pygfx and wgpu are you using?

**Comment by kevinyamauchi** [comment]
Ah sorry, should have included the information about my environment.

- OS: Mac OS 14.1 (Intel)
- Python: 3.10
- pygfx: 0.6.0
- wgpu: 0.19.2
- PySide6-essentials:  6.8.1


<details>
  <summary>pip list output</summary>

```
❯ pip list
Package            Version
------------------ -------
cffi               1.17.1
freetype-py        2.5.1
imageio            2.36.1
Jinja2             3.1.4
MarkupSafe         3.0.2
numpy              2.1.3
pillow             11.0.0
pip                24.2
pycparser          2.22
pygfx              0.6.0
pylinalg           0.4.1
PySide6_Essentials 6.8.1
rubicon-objc       0.4.9
setuptools         75.1.0
shiboken6          6.8.1
uharfbuzz          0.43.0
wgpu               0.19.2
wheel              0.44.0
```

</details>

**Comment by almarklein** [comment]
This seems oddly related to https://github.com/pygfx/wgpu-py/issues/650. I don't see how the axes helper would trigger this error 🤔

**Comment by almarklein** [comment]
We've moved up a few versions of wgpu, and have not seen any other reports like this, so I'm closing this.
